### ISSUE TITLE
Show Detailed Occurrences for rules failures 

### ISSUE THREAD

**Issue by myishay** [datreeio/datree#108]
**Is your feature request related to a problem? Please describe.**
As a user, I want to be able to have a clearer indication for the mistakes in my yaml manifests.

**Describe the solution you'd like**
Showing manifest's `metadata.name` and `kind` upon failure.

**Describe alternatives you've considered**
Manually iterating through all my manifest to find where exactly my config failed.

**Comment by eyarz** [comment]
here is a mock:
![Screen Shot 2021-07-29 at 12 41 36](https://user-images.githubusercontent.com/19731161/127469904-3e055e76-2149-42f9-89c4-3db823db52e2.png)

**Comment by eyarz** [comment]
live:
![image](https://user-images.githubusercontent.com/19731161/130630511-41417058-b1ec-473e-a93f-dd5cb095f338.png)
