### ISSUE TITLE
General datree question (pre-commit hook)

### ISSUE THREAD

**Issue by alexander-bruun** [datreeio/datree#121]
Is there any provided examples of how datree could be implemented as a pre-commit hook?

**Comment by eyarz** [comment]
You are right, we need to prepare one and add it to our docs 😅
I found an example in one of [our forks](https://github.com/pab1it0/datree#install-in-your-repo-as-a-pre-commit-hook) (don't forget to change the version to the newer one).
I didn't test it (yet), so I can't tell you if this working as expected, but it looks legit.

**Comment by alexander-bruun** [comment]
That was a very fast response, I will definitely look into it and try it out myself. Thanks a lot.

**Comment by alexander-bruun** [comment]
@eyarz I'm faily new to pre-commit hooks, so please let me know if I'm off the deep end or doing something wrong.

I did the following:
1) brew install pre-commit
2) in my repo directory I executed pre-commit install
3) I then added a .pre-commit-config.yaml to the root folder of my repo
4) I then run git commit and get the following error
![image](https://user-images.githubusercontent.com/87643857/128335439-1e9566bc-7113-41e5-8e5f-87f81b946254.png)


Here is content of my config file:

```
repos:
-   repo: https://github.com/datreeio/datree
    rev: 0.2.2
    hooks:
    -   id: datree
```


Note: 
The quick start guide to pre-commit works just fine:
![image](https://user-images.githubusercontent.com/87643857/128335866-55756a3c-8c07-42ff-af1b-0e59cec34ddd.png)

**Comment by eyarz** [comment]
🤔
To be frank, I never used this framework with a pre-commit hook.
I will give it a try by myself and keep you posted!

**Comment by eyarz** [comment]
I wrote a quick (and dirty) pre-commit hook:
![image](https://user-images.githubusercontent.com/19731161/128351509-a19b6017-1ab1-49a8-8a0a-309ce66baee3.png)

__How to implement:__
1. by default, every git repo has a `.git/hooks` folder (it is a hidden folder)
2. rename the `pre-commit.sample` file to just `pre-commit`
3. past inside the following code:
```
#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".yaml\{0,1\}$")

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

echo "\nValidating K8s files with Datree...\n"

for FILE in $STAGED_FILES
do
  datree test "$FILE"

  if [[ "$?" == 0 ]]; then
    echo "\033[32mDatree Passed: $FILE\033[0m"
  else
    echo "\033[41mDatree Failed: $FILE\033[0m"
    PASS=false
  fi
done

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass Datree but do not. Please fix the errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
```
4. make a change in a k8s yaml file and make a commit
5. the bash script will look for all the yaml files that are committed and will run `datree test [file]` on each one of them

This pre-commit is not relying on the [pre-commit framework](https://pre-commit.com/). I will check how to do it with the framework later, but in the meanwhile, this should be a _good enough_ solution for automatically running Datree on every (local) code change to K8s files.

**Comment by LarsBingBong** [comment]
It's totally fine if it does not work with the [pre-commit frameowk](https://pre-commit.com/) as we'll just use the `git config core.hooksPath PATH` configuration option to have a folder for git hooks included in X repo.

So cool

**Comment by alexander-bruun** [comment]
Very cool! @eyarz 

I just made some minor changes for the script to be #!/bin/sh compatible... specifically [[]] which is a bash thing:

```
#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".yaml\{0,1\}$")

if [ "$STAGED_FILES" = "" ]; then
  exit 0
fi

PASS=true

echo "\nValidating K8s files with Datree...\n"

for FILE in $STAGED_FILES
do
  datree test "$FILE" --ignore-missing-schemas

  if [ "$?" = 0 ]; then
    echo "\033[32mDatree Passed: $FILE\033[0m"
  else
    echo "\033[41mDatree Failed: $FILE\033[0m"
    PASS=false
  fi
done

if ! $PASS; then
  echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass Datree but do not. Please fix the errors and try again.\n"
  exit 1
else
  echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
fi

exit $?
```

Thanks a lot for the help!

**Comment by eyarz** [comment]
I leave this one open so I will remember to also add this to our docs :)

**Comment by eyarz** [comment]
added to docs: https://hub.datree.io/git-hooks
