### ISSUE TITLE
Datree fails when installing with brew

### ISSUE THREAD

**Issue by dimabru** [datreeio/datree#159]
**Describe the bug**
Any `datree` command fails

```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff20458cbe]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff20458cbe
stack: frame={sp:0x7ffeefbff528, fp:0x7ffeefbff578} stack=[0x7ffeefb805c8,0x7ffeefbff630)
0x00007ffeefbff428:  0x01007ffeefbff448  0x0000000000000004 
0x00007ffeefbff438:  0x000000000000001f  0x00007fff20458cbe
...
```

**To Reproduce**
1. Run command `brew install datree`
2. Run `datree`
3. Error is displayed

**Expected behavior**
Expecting `datree` to work

**Desktop (please complete the following information):**
 - OS: MacOS

**Datree version (run `datree verion`):**
 - Version: 0.9.0

**Additional context**  
I suspect this is because of go versioning issues during go build flow in homebrew-core. datree is not building well with version 1.17 and it looks like the default build is using 1.17 version

https://github.com/Homebrew/homebrew-core/blob/master/Formula/datree.rb

**Comment by myishay** [comment]
Related to this PR: https://github.com/Homebrew/homebrew-core/pull/84484

**Comment by SMillerDev** [comment]
What happens when you run `brew test datree`? Because I can't reproduce any error when running datree installed from brew.

**Comment by chenrui333** [comment]
I can actually reproduce this on my Mojave machine. 🤔

**Comment by chenrui333** [comment]
I believe this is related to https://github.com/golang/go/issues/45702 (which we have fixed bunch when we did the go 1.17 upgrade)

**Comment by chenrui333** [comment]
let me give 0.11.0 release a try in my local.

**Comment by chenrui333** [comment]
I filed a patch PR, I have verified it fixed my issue on my Mojave machine.

```
golang.org/x/sys/unix.ioctl(0x4547b89, 0x4, 0x1000000000018)
	golang.org/x/sys@v0.0.0-20210316164454-77fc1eacc6aa/unix/zsyscall_darwin_amd64.go:690 +0x39 fp=0xc00029f8c0 sp=0xc00029f890 pc=0x4361e59
```
