### ISSUE TITLE
Ability to hide "loading" animation

### ISSUE THREAD

**Issue by mahgo** [datreeio/datree#164]
**Is your feature request related to a problem? Please describe.**
I'm running datree in Azure Pipelines, and my logs are being filled up with lots of loading messages, such as:
```
| Loading... WWWWWWWWWWWWWW

/ Loading... WWWWWWWWWWWWWW

- Loading... WWWWWWWWWWWWWW

\ Loading... WWWWWWWWWWWWWW

| Loading... WWWWWWWWWWWWWW

/ Loading... WWWWWWWWWWWWWW

- Loading... WWWWWWWWWWWWWW

\ Loading... WWWWWWWWWWWWWW

| Loading... WWWWWWWWWWWWWW

/ Loading... WWWWWWWWWWWWWW

- Loading... WWWWWWWWWWWWWW

\ Loading... WWWWWWWWWWWWWW

| Loading... WWWWWWWWWWWWWW

/ Loading... WWWWWWWWWWWWWW

- Loading... WWWWWWWWWWWWWW

\ Loading... WWWWWWWWWWWWWW

```

**Describe the solution you'd like**
It would be good to be able to disable this with an optional argument.

**Comment by eyarz** [comment]
You have a good point there :)
I think the best way to do it is by updating our `--output simple` flag to also remove the loading animation.
WDYT?

**Comment by mahgo** [comment]
That would work for me!

**Comment by myishay** [comment]
A fix for this issue has been released and `--output simple` now also removes the loading animation. Enjoy!

**Comment by eyarz** [comment]
Just don't forget to update the CLI :)
`curl https://get.datree.io | /bin/bash`

**Comment by mahgo** [comment]
Works great, thanks!
