### ISSUE TITLE
k8s schema validation error: could not find schema for Ingress

### ISSUE THREAD

**Issue by mahgo** [datreeio/datree#166]
**Is your feature request related to a problem? Please describe.**
Datree test isn't working on my Ingress, with the following error: `k8s schema validation error: could not find schema for Ingress` It has an apiVersion of "networking.k8s.io/v1". Is this not supported? According to https://hub.datree.io/prevent-ingress-forwarding-traffic-to-single-container it looks like ingresses are supported in some form.

**Describe the solution you'd like**
Support for "networking.k8s.io/v1" ingresses.

**Comment by dimabru** [comment]
Hi @mahgo  
Any chance this is related to https://github.com/datreeio/datree/discussions/141?

**Comment by mahgo** [comment]
@dimabru Sorry for the delay. That did the trick!
