### ISSUE TITLE
"Ensure Deployment has more than one replica configured" shouldn't fail when replicas is omitted

### ISSUE THREAD

**Issue by mahgo** [datreeio/datree#185]
I think the policy "Ensure Deployment has more than one replica configured" - DEPLOYMENT_INCORRECT_REPLICAS_VALUE shouldn't fail when replicas is completely omitted. According to https://hub.datree.io/ensure-minimum-two-replicas this should only occur when replicas is set to 1. An example situation where you'd want to omit "replicas" is when using a Horizontal Pod Autoscaler to control the replicas instead.

**Comment by eyarz** [comment]
As far as I know, when `replicas` is not omitted, the default number of replicas per deployment is 1 (I also found [this on StackOverflow](https://stackoverflow.com/questions/49558538/kubernetes-set-deploment-number-of-replicas-based-on-namespace)), so I think this behavior is correct. But you're right, and we need to update the docs!

Regarding the scenario that you described (controlling the number of deployments with HPA), I think that in a case like that, the user can [turn off this rule](https://hub.datree.io/centralized-policy#uo-enable-and-disable-rules-in-a-policy).

WDTY?
