### ISSUE TITLE
Docs: Need to update the docker image name

### ISSUE THREAD

**Issue by NilimaC04** [datreeio/datree#189]
**Describe the bug**
From [Datree](https://hub.datree.io/) following the step [2](https://hub.datree.io/#mp-2-test-a-kubernetes-demo-manifest)
Docker image already pull from step [1](https://hub.datree.io/#a-1-install-datrees-cli-integration)
Using the Docker command:
![image](https://user-images.githubusercontent.com/16969949/135975257-a18c419d-5316-476c-9564-6648c9960770.png)

While running the docker command it shows an error `Unable to find image 'datree:latest' locally
docker: Error response from daemon: pull access denied for datree, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.` 

**To Reproduce**
1. Run command cat ~/.datree/k8s-demo.yaml | docker run -i datree test -
2. Hit enter
3. See error `Unable to find image 'datree:latest' locally
docker: Error response from daemon: pull access denied for datree, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.` 

**Expected behavior**
It should run the pulled docker image i.e datree/datree
The below command works fine:
cat ~/.datree/k8s-demo.yaml | docker run -i datree/datree test -

**Screenshots**
Not working:
![image](https://user-images.githubusercontent.com/16969949/135970555-e43be2fd-4bfe-4ecb-bcf7-bb7015aaeb23.png)

Working:
![image](https://user-images.githubusercontent.com/16969949/135971012-3ab4f327-d3db-4de0-84a9-4eec38a5b064.png)

**Desktop (please complete the following information):**
 - OS: Linux

**Datree version (run `datree verion`):**
 - Version: datree/datree:latest

**Additional context**  
If possible, include a YAML file to reproduce the bug.

**Comment by romanlab** [comment]
You're absolutely right. Until we fix the documentation you can use the following command:

`cat ~/.datree/k8s-demo.yaml | docker run -i datree/datree test -`

**Comment by eyarz** [comment]
I updated the doc, thank you!
