### ISSUE TITLE
Installation script continues even if download fails

### ISSUE THREAD

**Issue by romanlab** [datreeio/datree#195]
**Describe the bug**
The install script continues execution even if there are errors in the download process and the download fails

**To Reproduce**
1. curl https://get.datree.io | /bin/bash
2. interrupt internet(disable wifi during download)
3. See error

**Expected behavior**
Error message and non-zero exit code

**Screenshots**

![WhatsApp Image 2021-10-10 at 10 28 46](https://user-images.githubusercontent.com/1208902/136687121-2a794fc7-960c-476d-a2ff-9ab72b55b93b.jpeg)

**Desktop (please complete the following information):**
 - OS: Any

**Datree version (run `datree verion`):**
 - Version: Any

**Comment by ashish-ad** [comment]
I want to work on this.
Can I work on correcting the bash installation script?!

**Comment by romanlab** [comment]
@ashish-ad Yeah, sure. It'll be great.

There are 2 relevant files for this fix: [internal_install.sh](https://github.com/datreeio/datree/blob/staging/internal_install.sh) and [install.sh](https://github.com/datreeio/datree/blob/staging/install.sh)

**Comment by ashish-ad** [comment]
Hey Roman,
Are these two files different thing as I can see they seem to same but there are some changes internal_install.sh file that checking the os type as Linux and so on.. which file deals which what can I know that... 
Thank you

**Comment by dimabru** [comment]
Both files are pratically the same. You'll have to make sure the script fails if any line in the script returns exit code > 0. 
No need to make any changes in the os checking flow

**Comment by ashish-ad** [comment]
yeah got it!

**Comment by dimabru** [comment]
@ashish-ad 
please note that we deprecated the internal release flow in this pr https://github.com/datreeio/datree/pull/201
you'll see that the file `internal_install.sh` does not exist once you rebase from staging.
no need to make any changes to it

**Comment by ashish-ad** [comment]
Ok got it, then the changes only need to be made to the install.sh file right?!

**Comment by dimabru** [comment]
correct

**Comment by ashish-ad** [comment]
Can anyone review my PR?!
Suggestions If I have done something wrong...
