### ISSUE TITLE
Support installation for architectures other than x86_64

### ISSUE THREAD

**Issue by myishay** [datreeio/datree#203]
**Is your feature request related to a problem? Please describe.**
Installation script supports only x86_64 architecture. 386 and arm64 are not supported.

**Describe the solution you'd like**
Detect the machine's architecture and download the relevant release in the install script

**Additional context**
the relevant file that should be changed should be `install.sh` and `windows_install.ps1`

**Comment by amustaque97** [comment]
@myishay, I found this project interesting and would love to contribute. Could you please help me in understanding what does 386 mean?
what releases do we choose for 386 and arm64?
Thank you

**Comment by myishay** [comment]
Hi @amustaque97
`x86_64`, `arm64` and `386` are CPU architectures.
When downloading and installing datree using either `install.sh` for linux/darwin or `windows_install.ps1`, we should be able to determine what is the machine's CPU architecture and install the relevant release for it.
For example, a useful bash command for linux/darwin in this case would be: `uname -mp`

You can find the releases for the different architectures in our [Releases page](https://github.com/datreeio/datree/releases).
