### ISSUE TITLE
Automate contribution workflow

### ISSUE THREAD

**Issue by dimabru** [datreeio/datree#205]
**Is your feature request related to a problem? Please describe.**
When we receive code contributions from the community, before reviewing the code logic we have to do a manual set of checks that can be automated

**Describe the solution you'd like**
Add a bot to check for incompatibility with our contribution guidelines before getting a real person to review the code

**Additional context**
Adding automated labels can also be a nice addition - `ltgm`, `cla-yes/no`, `fix-commit-message`, etc.

**Comment by eyarz** [comment]
I will create a GitHub action workflow for that.
It will automatically verify the commit message and PR title.
@dimabru, anything else that you want it to do?

**Comment by dimabru** [comment]
@eyarz no, thanks a lot

**Comment by prasadkatti** [comment]
Hi. I would like to take a crack at this one.

**Comment by eyarz** [comment]
@prasadkatti, go for it :)
