### ISSUE TITLE
create a plugin for the pre-commit framework

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#217]
**Is your feature request related to a problem? Please describe.**
Sharing Datree's pre-commit hooks across projects can be painful because it requires copying and pasting unwieldy bash scripts.

**Describe the solution you'd like**
The [pre-commit framework](https://pre-commit.com/#introduction) was created to solve those hook issues.

**Additional context**
[Creating new hooks](https://pre-commit.com/#new-hooks).
Related to #125

**Comment by kevholmes** [comment]
Hi there! I've set up pre-commit hooks and worked with custom hooks before for a number of projects and really like it. I'd like to take a look into this.

**Comment by eyarz** [comment]
@kevholmes go for it :)

**Comment by kevholmes** [comment]
If I wanted to add some documentation on how to use the pre-commit hook where might be a good place? @eyarz

**Comment by eyarz** [comment]
Unfortunately, the docs are not open source (the platform that I'm using is not supporting it 😞), so just add your instructions to your PR and I will copy it from there (just like you did).
