### ISSUE TITLE
plug in framwork

### ISSUE THREAD

**Issue by Norelak** [datreeio/datree#219]
**Describe the bug**

**To Reproduce**
1. Run command '...'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]

**Datree version (run `datree verion`):**
 - Version: [e.g. 0.1.443]

**Additional context**  
If possible, include a YAML file to reproduce the bug.

**Comment by eyarz** [comment]
@Norelak I'm closing this bug because you didn't fill it at all, it's just our bug template.
