### ISSUE TITLE
Add developers guide for new contributers

### ISSUE THREAD

**Issue by dimabru** [datreeio/datree#222]
**Is your feature request related to a problem? Please describe.**
First-time contributers can face difficulties setting up the development environment

**Describe the solution you'd like**
A small and concise guide to `how to set up environment for development`

**Additional context**
A good example can be found here - https://helm.sh/docs/community/developers/

**Comment by rushikeshadhav** [comment]
Can I take this up ?

**Comment by romanlab** [comment]
@rushikeshadhav I think that it'll be better for someone from the maintainers team to do this one because it requires some deep knowledge with how the project is built and our coding standards. But it'll be great if you could validate that it's clear and easy to follow when it's done. WDYT?

**Comment by rushikeshadhav** [comment]
Yeah totally agree.
As I am a beginner to this project it will be great if you assign me some good first issue.
Would love to contribute to datree :)

**Comment by romanlab** [comment]
> Yeah totally agree. As I am a beginner to this project it will be great if you assign me some good first issue. Would love to contribute to datree :)

Sure, [this](https://github.com/datreeio/datree/issues/116) can be a great issue. @eyarz needs to elaborate a bit more on that and then you can take it.

**Comment by royhadad** [comment]
@rushikeshadhav 
I just finished adding the developer guide, let me know what you think :)
https://github.com/datreeio/datree/blob/main/DEVELOPER_GUIDE.md
