### ISSUE TITLE
Replace "stale app" with the "stale Action"

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#231]
**Is your feature request related to a problem? Please describe.**
Today, we are using the outdated [stale app](https://github.com/datreeio/datree/blob/staging/.github/stale.yml) to close stale issues

**Describe the solution you'd like**
use the [stale Action](https://github.com/actions/stale) that has more capabilities

**Additional context**
we should also configure the stale app to close stale PR

**Comment by prasadkatti** [comment]
I will take this up.
