### ISSUE TITLE
Autocompletion usage instructions in post install message

### ISSUE THREAD

**Issue by alexfedin** [datreeio/datree#263]
**Is your feature request related to a problem? Please describe.**
In order to have autocomplete for the CLI the user need to run the `completion` command

**Describe the solution you'd like**
Print a message to the user that he should run the completion command if he wants autocompletion enabled after the installation is finished

**Additional context**
I suggest adding a short description about the completion command here 
![image](https://user-images.githubusercontent.com/8144227/139843042-5fc725cb-cbeb-474c-9a8a-06d4f5f7bc09.png)

**Comment by amustaque97** [comment]
👋Hi, I would love to take a look at this.
