### ISSUE TITLE
Release workflow not waiting for travis build to end

### ISSUE THREAD

**Issue by dimabru** [datreeio/datree#273]
**Describe the bug**
Release flow of a new version is defined as a github workflow that sends a request to travis using http request. The workflow is not taking into account the time it takes for travis to finish the deployment step and instead shows releases as finished after a few seconds

**To Reproduce**
As maintainer, execute a release workflow. Notice that the release finishes a lot faster than the corresponding travis build that is still in progress

**Expected behavior**
Workflow should wait until travis build is finished

**Additional context**  
We probably need to add a step that waits for the specific travis build to finish and check its status

**Comment by kevholmes** [comment]
One comment here, you could make something that initiates the build in Travis, then waits n seconds, then re-checks the Travis build to see if it's finished and if it's not, repeat. Then finally when Travis says the build is done - you end your Actions workflow. The downside here is you'll actually be using up billable Actions minutes while your Workflow essentially does nothing but wait for Travis to finish. 

Where I'm going with this is perhaps you might want to consider using Actions to run the build workflow instead of Travis since by waiting for Travis to finish you'll be using up billable Actions time either way - even if your job sits there idle waiting for another outside process to finish. Might as well use those billable Actions minutes to actually build the binaries?

**Comment by dimabru** [comment]
Hi Kevin, I agree with you, but our use-case includes signing our cli with apple developer certificate, that's why we're using travis builds. they run on macos machines

The solution you suggested, polling the travis build and wait for it to finish is probably the best way to do it, unless we can somehow configure travis notifications to let us know when its done (?)

For now, we're ok with the costs of running Actions for polling purposes

**Comment by kevholmes** [comment]
> Hi Kevin, I agree with you, but our use-case includes signing our cli with apple developer certificate, that's why we're using travis builds. they run on macos machines
> 
> The solution you suggested, polling the travis build and wait for it to finish is probably the best way to do it, unless we can somehow configure travis notifications to let us know when its done (?)
> 
> For now, we're ok with the costs of running Actions for polling purposes

Ooohh ok, I am familiar with the challenges of building and signing macOS builds! One thing to note is that Actions does offer macOS [10.x](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) and [11.x](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md) runners. You should be able to store your private signing key in Actions Secrets as a base64 encoded blob at rest and then convert back to plain text file for signing purposes. I have had to do similar things for builds of iOS and macOS apps going to the Apple Store.

**Comment by dimabru** [comment]
cool, thanks for the info!
I think moving the builds is a bit out of scope for now but we can certainly take that into consideration going forward.
Do you see any other potential challenges should we decide to make that transition?

**Comment by kevholmes** [comment]
Just quicking reviewing the Travis config yml and it looks pretty straightforward. The Actions 10.15 macOS image has Xcode 12.4 by default so it's pretty close to where you are in Travis at 12.5. Go 1.17 shouldn't be an issue either. Looks like [goreleaser](https://github.com/goreleaser/goreleaser-action) has a relatively popular Action you could utilize, also.

A bigger task for sure but IMO would make the whole build/release process more transparent to external contributors and internal datree hackers alike :)

**Comment by kevholmes** [comment]
Is anyone actively working on a PR for this issue - or could I take it? @royhadad @dimabru

**Comment by dimabru** [comment]
yeah, @royhadad is on it
