### ISSUE TITLE
Can't install DaTree on windows11(x64)

### ISSUE THREAD

**Issue by helper-uttam** [datreeio/datree#287]
Hi there I'm having problem in installing `datree` on win11(x64) when I ran the command
 ```curl https://get.datree.io | /bin/bash```
**Result :**
```
[V] Downloaded Datree
unzip:  cannot find or open datree-latest.zip, datree-latest.zip.zip or datree-latest.zip.ZIP.
cp: cannot stat 'datree-latest/datree': No such file or directory
/bin/bash: line 29: sudo: command not found
rm: cannot remove 'datree-latest.zip': No such file or directory
[V] Finished Installation

 Usage: $ datree test ~/.datree/k8s-demo.yaml
 Using Helm? => https://hub.datree.io/helm-plugin
```
then I tried `datree verison` but It says `bash: datree: command not found`

then i tried `$ iwr -useb https://get.datree.io/windows_install.ps1 | iex` 
Output
```
bash: iwr: command not found
bash: iex: command not found
```

**Comment by alexfedin** [comment]
Hi @helper-uttam, to install datree on windows you need to run the command `iwr -useb https://get.datree.io/windows_install.ps1 | iex`, but from what you describe you tried to run `curl https://get.datree.io | /bin/bash` which is a linux command and it's not supposed to work on windows OS.

Then I see that you ran the `iwr -useb https://get.datree.io/windows_install.ps1 | iex` command but got the errors: 
`bash: iwr: command not found
bash: iex: command not found`

This command is supposed to run on Windows and not supported on Linux.
You get these errors when you try to run the command on Linux.


Do you run by chance a Linux virtual machine on Windows? if so what is the linux version you are running?
If that's not the case, make sure you are running the correct command for the OS you are using


 (This is described in our docs homepage: https://hub.datree.io/#a-1-install-datrees-cli-integration)

**Comment by helper-uttam** [comment]
> Hi @helper-uttam, to install datree on windows you need to run the command `iwr -useb https://get.datree.io/windows_install.ps1 | iex`, but from what you describe you tried to run `curl https://get.datree.io | /bin/bash` which is a linux command and it's not supposed to work on windows OS.
> 
> Then I see that you ran the `iwr -useb https://get.datree.io/windows_install.ps1 | iex` command but got the errors: `bash: iwr: command not found bash: iex: command not found`
> 
> This command is supposed to run on Windows and not supported on Linux. You get these errors when you try to run the command on Linux.
> 
> Do you run by chance a Linux virtual machine on Windows? if so what is the linux version you are running? If that's not the case, make sure you are running the correct command for the OS you are using
> 
> (This is described in our docs homepage: https://hub.datree.io/#a-1-install-datrees-cli-integration)

Nopes, I'm not using any linux vm. But I tried all the commands that are for windows like `iwr -useb https://get.datree.io/windows_install.ps1 | iex`. But it didn't worked for me

**Comment by eyarz** [comment]
Did you try it on PowerShell (as admin)?

**Comment by helper-uttam** [comment]
Yes obviously! That was the first thing I have done.

**Comment by eyarz** [comment]
🤔 interesting.
Can you please run `$PSversionTable` inside your PowerShell and paste here a screenshot
Like that:
![image](https://user-images.githubusercontent.com/19731161/143219151-5f94575a-c868-4d65-b2f2-5c51f0cf654a.png)

**Comment by helper-uttam** [comment]
Here it is @eyarz 
![Screenshot (83)](https://user-images.githubusercontent.com/72701081/143248661-895716ef-474e-4168-958d-ca5b17f63acc.png)

**Comment by eyarz** [comment]
I see you have an [error in your terminal](https://stackoverflow.com/questions/41117421/ps1-cannot-be-loaded-because-running-scripts-is-disabled-on-this-system) - maybe this is what causing the installation problem...?

**Comment by helper-uttam** [comment]
Hurray! Installed @eyarz ! Thankyou so much :)

**Comment by beingtechsavy** [comment]
Hello everybody,
I am installing datree but I am running into mishaps.
I tried the installation command for windows and switched to powershell and tried the path setup command.
Yet it is throwing error saying datree is not recognized when I run 'datree'.
Please help! :)
![Screenshot (57)](https://user-images.githubusercontent.com/111677648/189755455-c5ea8aa9-57f6-4b2a-95cb-1741aaaa2539.png)

**Comment by eyarz** [comment]
For future reference, this is how @beingtechsavy solved his issue:
https://github.com/datreeio/datree/issues/788
