### ISSUE TITLE
installation with "curl" doesn't work with mac m1 chip

### ISSUE THREAD

**Issue by royhadad** [datreeio/datree#304]
**description**
installation with "curl" doesn't work with mac m1 chip

**Steps to reproduce the behavior:**
1. open a mac machine with an m1 chip
2. run the datree installation command: "curl https://get.datree.io | /bin/bash"
3. run "datree --help"
4. you will get an error: "datree: command not found"

**Expected behavior**
Expecting the datree cli to be installed

 - OS: MacOS, m1 chip
 - Version: 0.14.62

**Comment by eyarz** [comment]
@royhadad what's the best way to address it?
because you listed it as `good first issue`, can please elaborate on which files/scripts need to be updated?

**Comment by royhadad** [comment]
Steps to solve this issue:

In .goreleaser.yml, add a release for mac + m1, should result in a release with the name of:
datree-cli_0.0.1_Darwin_arm64.zip 

**nice to have:**
in brew_formula_generator.sh:
add a check for the mac architecture, and download the correct version
