### ISSUE TITLE
Missing invalid schema version notification

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#305]
**Describe the bug**

**To Reproduce**
1. Run command `datree test k8s-demo.yaml -s=1.15`
2. See error: `k8s schema validation error: could not find schema for X`

**Expected behavior**
the schema version that I passed (`1.15` instead of `1.15.0`) is invalid.
therefore, I should get some kind of indication about that.

**Screenshots**
![image](https://user-images.githubusercontent.com/19731161/145391968-2c16fade-97a3-42b3-bec3-82e32f0f4fd4.png)

**Desktop (please complete the following information):**
 - OS: MacOs

**Datree version (run `datree version`):**
 - Version: 0.14.49

**Comment by Abhra303** [comment]
@eyarz will it work?

![datree-invalid-schema-version](https://user-images.githubusercontent.com/75240995/147056603-01bac5a9-02ea-4c88-9ea2-9f11fc967b13.png)

**Comment by eyarz** [comment]
LGTM!
open a PR and someone for the maintainers team will review it :)

**Comment by Abhra303** [comment]
okay :)
