### ISSUE TITLE
Installing in Github Action CI for Ubuntu Failed

### ISSUE THREAD

**Issue by sookeke** [datreeio/datree#308]
**Describe the bug**
This started yesterday, My CI pipeline with github action been working using datree but started failing datree installing steps since yesterday

**To Reproduce**
      - name: Install Datree
        run: curl https://get.datree.io | /bin/bash

**Expected behavior**
[V] Downloaded Datree
[V] Finished Installation

**Screenshots**
![image](https://user-images.githubusercontent.com/76934070/145462269-81f21a3f-4f17-4eff-a003-3a6ffce74752.png)

**Desktop (please complete the following information):**
 - OS: Linux - ubuntu
**Datree version (run `datree version`):**
 - Version: [e.g. 0.1.443]

**Additional context**  
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8s-policy-check:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Datree
        run: curl https://get.datree.io | /bin/bash
        
      - name: Run Datree's policy check
        run: datree test ~/.datree/k8s-demo.yaml

**Comment by eyarz** [comment]
you are right, I'm also able to reproduce it:
https://github.com/eyarz/random-gif-action/runs/4476319902?check_suite_focus=true

someone will look into it ASAP.

**Comment by myishay** [comment]
@sookeke I just pushed a fix, can you please check this again and let us know if it is fixed on your side?

**Comment by sookeke** [comment]
@myishay  this is fix. thank you
