### ISSUE TITLE
404 Error on homepage

### ISSUE THREAD

**Issue by DhairyaBahl** [datreeio/datree#317]
### https://www.datree.io/
Error on this page.

![image](https://user-images.githubusercontent.com/71627983/145691913-8e5aa116-f837-429d-9365-9cf050ee664f.png)

**Comment by DhairyaBahl** [comment]
Kindly assign this issue to me.

**Comment by eyarz** [comment]
@DhairyaBahl thank you for reporting that!
This website (datree.io) is not hosted on GitHub, so you can't help with this issue, but thank you for offering your help :)

**Comment by DhairyaBahl** [comment]
@eyarz No issues ! Glad to be helpful ! Cheers 🍻
