### ISSUE TITLE
Is CLA mentioned in the Contributing.md file working?

### ISSUE THREAD

**Issue by Abhra303** [datreeio/datree#326]
**Describe the bug**
I am trying to sign the CLA form mentioned in [Contributing.md](https://github.com/datreeio/datree/blob/ada7baa263f7dee8b43c99bc50868bf6b90e0857/CONTRIBUTING.md#cla) but it is showing this -
```
There is no CLA to sign for datreeio/datree
(could not find linked item for owner datreeio and repo datree)
```

**To Reproduce**
1. Go to [Contributing.md](https://github.com/datreeio/datree/blob/ada7baa263f7dee8b43c99bc50868bf6b90e0857/CONTRIBUTING.md#cla)
2. Click on [simple click through form](https://cla-assistant.io/datreeio/datree)
3. See error

**Expected behavior**
It should give me a form.

**Screenshots**

![image](https://user-images.githubusercontent.com/75240995/145706653-b825ab5e-a949-4e8c-97ac-fadea9bf7e07.png)

**Desktop (please complete the following information):**
 I don't think it depends on any desktop

**Comment by royhadad** [comment]
thank you for notifying us, will be fixed soon
