### ISSUE TITLE
Hide Token in CLI output

### ISSUE THREAD

**Issue by SuyashSonawane** [datreeio/datree#340]
**Is your feature request related to a problem? Please describe.**
When the `datree test test.yaml` is executed the CLI prints the details as expected but also has the token visible to everyone.
Imagine a case where a YouTuber is explaining Datree's uses but has not yet created his account on [app.datree.io](https://app.datree.io/login), someone from the viewer uses his(YouTuber) token to create an account with their(viewer) credentials.
This can lead to confusion if the viewer makes any changes to the configurations associated with that token.

**Describe the solution you'd like**
Hide the token until command like `datree --config` is ran which will output the token.

**Comment by AvinashNayak27** [comment]
But I don't think one can login with other's token As Token helps only in testing policies enabled by the Owner,If a viewer uses YouTuber's Token He can only test his Manifest Files Enabled by YouTuber but he can't change or edit the configurations of Policies

**Comment by royhadad** [comment]
I can see 2 interesting solutions:
1. in the dashboard url, create a clickable link that hides the actual url
something like this: [click here to view the dashboard](https://app.datree.io/login?cliId=inhyrhjrnafgsdfgdfgfdhciApc)

2. add an opt-in flag to the test command, which will hide the dashboard url
something like this: `datree test ~/.datree/k8s-demo.yaml --no-dashboard-url`

**Comment by eyarz** [comment]
@SuyashSonawane, thank you for the feedback!

@AvinashNayak27 is correct.
I think the word `token` is confusing in this context because if a user will use a different user token, he will not be able to connect to the account with a "stolen" token, he will only be able to pull his policy and use it against his manifest files.

Having said that, I agree that it's something that needs to be handled better.
We will start working on a Token Management system soon that will solve those issues.

**Comment by SuyashSonawane** [comment]
Apologizes if I'm wrong here, what I thought before creating the account the clientId which is in your machine is not mapped to any account. Once you signup with that link from the cmd your credentials gets mapped with that clientId/token.

Thanks @royhadad and @eyarz for quick solution and response 🙌

**Comment by eyarz** [comment]
> Apologizes if I'm wrong here, what I thought before creating the account the clientId which is in your machine is not mapped to any account. Once you signup with that link from the cmd your credentials gets mapped with that clientId/token.

yes, you're right!
