### ISSUE TITLE
Show all possible errors during the `YAML validation` step

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#349]
**Is your feature request related to a problem? Please describe.**
When more than one yaml syntax issues are introduced in the same file, the yaml validation step will only show one error, and only after it's fixed, I will see the next error. 

**Describe the solution you'd like**
Getting (a list of) all yaml syntax errors (instead of one) during the yaml validation step.

**Additional context**
More info can be found [here](https://github.com/datreeio/datree/issues/116#issuecomment-1001624005).

**Comment by amustaque97** [comment]
Hi team, I would love to give it a shot.

**Comment by eyarz** [comment]
Perfect, go for it!

**Comment by amustaque97** [comment]
:wave: @eyarz, looks like this is a limitation with the `gopkg.in/yaml.v3` package. I ran a simple test and read the doc. Currently, there is no way to get all errors in a single run.

<img width="1790" alt="Screenshot 2022-01-10 at 10 14 43 PM" src="https://user-images.githubusercontent.com/21127788/148805992-ccc9b508-0e7a-40e5-a6cd-7b6c2af2a03e.png">


Please share your thoughts!

**Comment by noaabarki** [comment]
Hey @amustaque97, nice to e-meet you!

You are correct. 👏🏻
I did some research too and apparently gopkg.in/yaml.v3 decodes the yaml by parsing, unmarshal it and validate its content according to a given interface. If (and when) from some reason the parsing gets failed the package throws a panic error. Unfortunately, any retries mechanism or attempt to bypass this won’t help us. The “bad news” is that it’s not true for gopkg.in/yaml.v3 only; other packages such as "github.com/goccy/go-yaml" works the same way. 😳

As I see it we have two options:
1. To try to find different package/tool that we can use.
2. Consider opening an issue in "github.com/goccy/go-yaml"/gopkg.in/yaml.v3.

What do you think?

**Comment by amustaque97** [comment]
@noaabarki, glad to e-meet you too! 😃 

I don't think there are any existing package that will print all errors in a single execution. Since `yaml` parser pareses code line by line. Moreover moving to different package I won't recommend. 

We should open an issue in `github.com/goccy/go-yaml"/gopkg.in/yaml.v3`  and keep an eye on the discussion/PR happening around similar lines.

WDYT?

**Comment by noaabarki** [comment]
Hey @amustaque97, I agree. I'll open an issue on our behalf :) 
The issue can be found [here](https://github.com/go-yaml/yaml/issues/816).
