### ISSUE TITLE
Register test command flags with pointers 

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#379]
**Describe the solution you'd like**
Cleanup code and avoid unnecessary allocation by register the flags in separated function and using Cobra’s `StringVar, BoolVar...` for pointers.

**Requirements** 
Golang basic level.

**“How to implement” Suggestion**
In `cmd/test/main.go`
1. Add constructor to `TestCommandFlags`.
    
    ```go
    func NewTestCommandFlags() *TestCommandFlags {
    	return &TestCommandFlags{
    		...
    	}
    }
    ```
    
2. 2. Add  `AddFlags` method to `TestCommandFlags` that accepts cobra’s command as argument and registers flags for the command and bind the flags to `TestCommandFlags`.
    
    ```go
    type TestCommandFlags struct {
    	Output               string
    	K8sVersion           string
    	IgnoreMissingSchemas bool
    	....
    }
    
    // AddFlags registers flags for a cli
    func (flags *TestCommandFlags) AddFlags(cmd *cobra.Command) {
    	cmd.Flags().StringVarP(&flags.Output, "output", "o", "", "Define output format")
    	cmd.Flags().StringVarP(&flags.K8sVersion, "schema-version", "s", "", "Set kubernetes version to validate against. Defaults to 1.18.0")
    	cmd.Flags().StringVarP(&flags.PolicyName, "policy", "p", "", "Policy name to run against")
    	cmd.Flags().BoolVarP(&flags.OnlyK8sFiles, "only-k8s-files", "", false, "Evaluate only valid yaml files with the properties 'apiVersion' and 'kind'. Ignore everything else")
    
    	// kubeconform flags
    	cmd.Flags().StringArrayVarP(&flags.SchemaLocations, "schema-location", "", []string{}, "Override schemas location search path (can be specified multiple times)")
    	cmd.Flags().BoolVarP(&flags.IgnoreMissingSchemas, "ignore-missing-schemas", "", false, "Ignore missing schemas when executing schema validation step")
    }
    ```
    
3. Create `NewTestCommandFlags` and register using the new function you have created. 
    
    ```go
    
    func New(ctx *TestCommandContext) *cobra.Command {
    	--> testCommandFlags := NewTestCommandFlags()
    	testCommand := &cobra.Command{
    		...
    	}
    
    	--> testCommandFlags.AddFlags(testCommand)
    	return testCommand
    }
    
    ```

**Comment by Kanika637** [comment]
Hey @noaabarki, Can you please guide me on how can I get started with this one?

**Comment by noaabarki** [comment]
Hi @Kanika637! Sure! Feel free to use our community [slack channel](https://datreecommunity.slack.com/ssb/redirect) for raising any questions 😎

**Comment by imrushi** [comment]
Hi @noaabarki, I can try to resolve/clean up the code. If anyone already working on it please let me know. 🙂

**Comment by noaabarki** [comment]
Hey @imrushi! As far as I know, @Kanika637 removed her assignment on this one, and no one yet submitted a PR for that. You got it :)

**Comment by imrushi** [comment]
Hi @noaabarki, Can we close this issue as it got resolved and merged?
