### ISSUE TITLE
Improve test command coverage for path argument issues

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#383]
**Describe the solution you'd like**
Add tests for failures flows regarding path argument in test command`datree test <path>`

Basic use cases to cover

Case: Given path contains zero files

- should print "No files detected”

Case: Given path contains YAML files that are not Kubernetes resources

Empty evaluation results

- should create evaluation
- should request evaluation
- should print returned results

Case: Given path with multiple resources in single file

- should create evaluation
- should request evaluation
- should print returned results

**Requirements** 
Golang basic level.

**Comment by Abhra303** [comment]
Hey @noaabarki  I would like to try this :)

**Comment by noaabarki** [comment]
@Abhra303 awesome, it's yours 👑

**Comment by Abhra303** [comment]
Hello @noaabarki,

#381 , #382 and this issue are very close to each other. I mean, the test codes might be very similar. So would you mind if I cover all the test cases in a single PR?

**Comment by noaabarki** [comment]
@Abhra303, yes you're right they are very close, do you prefer to do it all together? 
The reason why I separated them was that I was worried we'd end with a giant PR. Small and contained PRs are always better, especially when it comes to unit tests in Go which are usually hard to read and understand.

**Comment by Abhra303** [comment]
> The reason why I separated them was that I was worried we'd end with a giant PR. Small and contained PRs are always better, especially when it comes to unit tests in Go which are usually hard to read and understand.

Hmm, That's sensible. 
Okay, I will make separate PRs for them. Would that be okay?

**Comment by noaabarki** [comment]
Sounds good :)
