### ISSUE TITLE
Create a Tekton Task that runs the Datree CLI

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#388]
As part of our effort to [support various plugins](https://github.com/datreeio/datree/issues/125), we would like to create a Tekton Task that will enable users to run the Datree CLI as part of their Tekton pipeline/s.

**Requirements**:
* Knowledge of yaml.
* No knowledge of the Datree codebase is needed.

**Resources**:
To get started with creating a Tekton Task, see the [Tekton readme](https://github.com/tektoncd/pipeline/blob/main/docs/tutorial.md).
For all Datree-related resources, see the [Datree documentation](https://hub.datree.io/).

**Specification**:
1. The task should support using a [Datree CLI token](https://hub.datree.io/account-token) in two ways:
   * Setting the token at pipeline level, i.e. as an environment variable.
   * Passing the token directly into the task.
2. The task should run “datree test” on a user-specified file/directory (see [relevant Datree documentation](https://hub.datree.io/cli-arguments#v2-running-a-policy-check)), and fail the pipeline if any of the files failed Datree’s policy check.
3. The task should be configurable with regards to the available CLI options. The supported options should be:
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a99a9add-7fff-cfc5-feb0-0bba15c896c0"><div dir="ltr" style="margin-left:-61.5pt;" align="left">

Flag | Alias | Values | Description
-- | -- | -- | --
--output | -o | json, yaml, xml | Output the policy check results in the requested format
--output | -o | simple | Output the policy check results in simple text (without emoji or colors)
--schema-version | -s | e.g. "1.20.0" | Set Kubernetes version to validate against.Defaults to 1.18.0 (default "1.18.0")
--ignore-missing-schemas | N/A | N/A | Skip files with missing schemas instead of failing the schema validation check
--policy | -p | e.g. staging | Specify which policy to execute (by policy name)
--only-k8s-files | N/A | N/A | Skip all non-K8s files.Especially useful when scanning a dir with K8s and other config files: `datree test *.yaml --only-k8s-files`

</div></b>
</div></b>

4. The task should include an example workflow that uses it.
5. Once finished, publish the task to the Tekton hub.

**Comment by avinashupadhya99** [comment]
Hi @hadar-co , I will be working on this issue. Thanks!

**Comment by avinashupadhya99** [comment]
The task is created and documented at https://github.com/avinashupadhya99/catalog/tree/add-datree-task/task/datree/0.1 I will make the PR to the [catalog repo](https://github.com/tektoncd/catalog) once the task is approved by you folks. 

> Please note that the installation link in the README will not work as the PR is not yet merged. You can use `https://raw.githubusercontent.com/avinashupadhya99/catalog/add-datree-task/task/datree/0.1/datree.yaml` to install

**Comment by eyarz** [comment]
@hadar-co can we close this?
