### ISSUE TITLE
Add a --not-strict flag to the CLI

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#402]
**Is your feature request related to a problem? Please describe.**
The kubeconform cli provides a "-strict" flag:
-strict
        disallow additional properties not in schema

By default, the Datree cli uses this flag during schema validation, thus disallowing additional properties.

**Describe the solution you'd like**
Add a --not-strict flag to the Datree cli that does not set this flag when using kubeconform for schema validation.

**Comment by SuperAayush** [comment]
Hey, @hadar-co I want to work on this issue can you please guide me on how I can get started.

**Comment by hadar-co** [comment]
Hey @SuperAayush, awesome thanks :)

As you can see in the following code, we pass (Strict: true) always.
A '--not-strict' flag should be added to the "test" command so that if it's passed, 'Strict' should be set to false instead of true.
https://github.com/datreeio/datree/blob/4c5bdff01f44fbb946d309794e11085acda3c115/bl/validation/k8sValidator.go#L143-L146

Please take a look at the way the variable **"ignoreMissingSchemas"** is handled, it should be very similar.

**Comment by SuperAayush** [comment]
I have made the PR sir thank you so much @hadar-co and @dimabru Sir for helping me this much and I am looking forward to making some more amazing contribution to datree as well as open-source.

**Comment by hadar-co** [comment]
@SuperAayush Thank you for contributing! Following our conversation, we will complete the remaining work. See you on the next one ;)

**Comment by myishay** [comment]
Hi @hadar-co @dimabru 
Regarding the flag naming, I think it would be better defining the flag as `--schema-not-strict`
