### ISSUE TITLE
Create a CircleCI orb that runs the Datree CLI

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#404]
As part of our effort to [support various plugins](https://github.com/datreeio/datree/issues/125), we would like to create a CircleCI orb that will enable users to run the Datree CLI as part of their workflow/s.

**Writing a CircleCI orb:**
* Requires knowledge of yaml.
* Does not require knowledge of the Datree codebase.

To get started with creating a circleci orb, see the [circleci orb documentation](https://circleci.com/docs/2.0/orb-author-intro/).
For all Datree-related resources, see the [Datree documentation](https://hub.datree.io/).

**Specification and requirements:**
* The orb should support setting a [Datree CLI token](https://hub.datree.io/account-token).
* The orb should include an example workflow that uses it.
* The orb should run “datree test” on a specific user-specified file/directory (see [relevant Datree documentation](https://hub.datree.io/cli-options#v2-input)).
* The orb should support all of the “datree test” CLI arguments, as described in the [documentation](https://hub.datree.io/cli-arguments).
* The orb should fail the workflow if any of the files failed Datree’s policy check.
* Once finished, publish the orb to the [orb registry](https://circleci.com/developer/orbs).

**Comment by techwithbhavya** [comment]
Hello sir, @hadar-co I want to work on this issue. Will you guide me towards this issue?

**Comment by hadar-co** [comment]
@bhavyastar Sure :)
following our conversation, please read up on CircleCI orbs and let me know if you need any assistance

**Comment by noaabarki** [comment]
Hi @bhavyastar! Just wanted to ping you regarding this issue. Do you need any guidance? Feel free to reach out :)

**Comment by hadar-co** [comment]
assigning to @naorpeled

**Comment by naorpeled** [comment]
😎

**Comment by naorpeled** [comment]
The orb is ready to be used :)
https://github.com/naorpeled/datree-circleci-orb

**Comment by hadar-co** [comment]
Awesome! Thanks @naorpeled :)
