### ISSUE TITLE
Move fixtures out from the internal folder

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#407]
**Describe the solution you'd like**
Move the `fixtures` folder to outside `internal` and place it under root as a “sibling” to `internal`, `pkg`, `cmd` and the rest. The reason why is because `internal/` is a special directory name recognized by the go tool which will prevent one package from being imported by another unless both share a common ancestor. 

**Requirements**
Golang basic level.

**Comment by arsheelsheikh** [comment]
@noaabarki Hi I would like to work on this issue, can you please guide me on how I can get started.
and where would the Golang be required when it is only to move the folder.

**Comment by techwithbhavya** [comment]
Hello ma'am, @noaabarki Will you assign this to me?

**Comment by Kanika637** [comment]
Hey, @noaabarki  I would like to work on this issue, will u guide me towards this.

**Comment by noaabarki** [comment]
Hi @arsheelsheikh and @Kanika637! Thank you for your will to contribute to our project, you're the best!👑  It appears that @bhavyastar already submitted a PR for this issue. However, we have plenty of other "good-first-issue" feature requests waiting to be assigned. If there's any issue that you’d like to take don’t hesitate to ask for help and reach out in our community slack channel 😍
