### ISSUE TITLE
Add exit code/s to CLI to distinguish between different results

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#415]
Currently the CLI:
* Returns 0 when a test does not find any misconfigurations.
* Returns 1 in any other case.

The CLI should:
* Return a certain error code (i.e. 1) when a test finds misconfigurations in a file.
* Return a different error code (i.e. 2) when it is used incorrectly, i.e. when an invalid argument is passed to it.

**Comment by dimabru** [comment]
This might affect existing plugins that are using datree. We need to make sure they don't break

**Comment by Kanika637** [comment]
Hey @hadar-co would you please guide me to work on this one

**Comment by hadar-co** [comment]
@Kanika637 Hey, thanks for your reply! This task has already been done and is waiting for review.

Would you like me to assist in finding another task for you? :)

**Comment by Kanika637** [comment]
Sure @hadar-co  Please help me find another task...Thanks

**Comment by Kanika637** [comment]
Sure @hadar-co, I would love to.
