### ISSUE TITLE
Validate test command args before cobra.Run  

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#433]
**Describe the solution you'd like**

Validate test commands arguments before Run. This pattern will allow us to governance  behaviors such as flags/arguments validation in all commands. Additionally, this should make the code easier to understand and maintain. 

**Requirements**
Golang basic level.

**“How to Implement” suggestion**

- `cmd/test/main.go` 
You can see that in `test()` we check if reading files from the `stdn` is necessary. Before, we check the commands args. If they’re invalid we throw an error. This issue is to move this logic and any other arguments validation(such as `Validate()` function)  to `cobra.Command` Args field.
- The final result should be something like this:
    
    ```go
    Args: func(cmd *cobra.Command, args []string) error {
    			if len(args) < 1 {
    				return fmt.Errorf("requires at least 1 arg")
    			} else if args[0] == "-" {
    				return fmt.Errorf(fmt.Sprintf("Unexpected args: [%s]", strings.Join(args[1:], ",")))
    			}
    
    			return testCommandFlags.Validate()
    }
    ```

**Comment by amustaque97** [comment]
Hi, I would love to work on this and related issues. 🚀

**Comment by noaabarki** [comment]
Hi @amustaque97, you got it 👍🏼
