### ISSUE TITLE
Validate publish command args before cobra.Run

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#434]
**Describe the solution you'd like**

Validate test commands arguments before Run. This pattern will allow us to governance behaviors such as flags/arguments validation in all commands. Additionally, this should make the code easier to understand and maintain. 

**Requirements**
Golang basic level.

**“How to Implement” suggestion**

See [issue](https://github.com/datreeio/datree/issues/433) as a reference.

**Comment by just-injoey** [comment]
is anyone working on this issue?

**Comment by adifayer** [comment]
@just-injoey Still up for grabs, would you like to take it? :)

**Comment by anubha-v-ardhan** [comment]
Hi @adifayer 
I'm new to golang and would like give this a try. Can I take this?

**Comment by anubha-v-ardhan** [comment]
Hey @adifayer @noaabarki 
Can you tell me how we can achieve this, I want to work on this issue.

**Comment by adifayer** [comment]
@anubha-v-ardhan sure, you got it! 
Did you check out the [issue](https://github.com/datreeio/datree/issues/433) that we added as a reference?

**Comment by KiranSatyaRaj** [comment]
Is this still in the works? after going through the referenced issue, I get the gist of what needs to be done, if anyone isn't working on this issue. I can take this up, can you give me your opinion on this @noaabarki?

**Comment by noaabarki** [comment]
Hi @KiranSatyaRaj, yes this is still relevant. You got it 🥳

**Comment by noaabarki** [comment]
Hi @KiranSatyaRaj, this is still relevant, but we don't want to hijack  @anubha-v-ardhan work 😇. @anubha-v-ardhan are you still working on it?

**Comment by rakshitgondwal** [comment]
Hey! There hasn't been any progress on this for a long time. Can I take this up? @noaabarki

**Comment by eyarz** [comment]
you're right.
go for it!

**Comment by rakshitgondwal** [comment]
Hey @eyarz! Thanks a lot for assigning me this issue.
I just went through the codebase and the other [issue](https://github.com/datreeio/datree/issues/433) mentioned above.
I had a question, where do I need to move the logic of validating the arguments in the `cmd/publish.main.go`?

**Comment by royhadad** [comment]
I think that the idea is to move the validation into the `Args` function. but it seems that it already happens there (only 1 argument, which is the path to the PaC.yaml file)
https://github.com/datreeio/datree/blob/4cb4d835b8fe8f6b6abefedfad5220b860ec416a/cmd/publish/main.go#LL63C4-L69C5

@noaabarki is this issue still relevant?

**Comment by noaabarki** [comment]
@rakshitgondwal, @royhadad, both of you are correct. Unfortunately, this issue has already been resolved and is no longer relevant. Sorry for the trouble.
