### ISSUE TITLE
Remove new line and capital letters from errors

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#435]
**Describe the solution you'd like**

We want to make sure our error strings follow a set of guidelines to ensure uniformity and good composability. Quoting Go Code Review Comments:
> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use `fmt.Errorf("something bad")` not `fmt.Errorf("Something bad")`, so that `log.Printf("Reading %s: %v", filename, err)` formats without a spurious capital letter mid-message.
> 

Resource: [https://staticcheck.io/docs/checks/#ST1005](https://staticcheck.io/docs/checks/#ST1005)

**Requirements**
Golang basic level.

**Comment by HillaShx** [comment]
@noaabarki May I be assigned this issue?

**Comment by noaabarki** [comment]
Hey @HillaShx! Sure, you got it!!🏆
