### ISSUE TITLE
Validate config command args before cobra.Run

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#441]
**Describe the solution you'd like**

Validate test commands arguments before Run. This pattern will allow us to governance behaviors such as flags/arguments validation in all commands. Additionally, this should make the code easier to understand and maintain. 

**Requirements**
Golang basic level.

**“How to Implement” suggestion**

See [issue](https://github.com/datreeio/datree/issues/433) as a reference.

**Comment by SuperAayush** [comment]
Hey @noaabarki, I would like to work on this issue can you help me out on how to get started with it.

**Comment by noaabarki** [comment]
Hi @SuperAayush! Apparently, this issue accidentally has been left unassigned but looks like it was already fixed and merged to `main`. I'll close it now, I'm sorry for the misunderstanding. We have plenty of other issues and we always look for contributions. Don't hesitate to reach out if you have any question :)
