### ISSUE TITLE
Add test coverage for extractor package

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#443]
**Describe the solution you'd like**

Add test coverage for package extractor. See `pkg/httpClient` as a reference.

For `ToAbsolutePath`, the test cases are already exists but for  `ExtractConfigurationsFromYamlFile` the test cases should include:

- Case: empty(””) path argument
    
    Expected: should return invalid file with returned `ToAbsolutePath` error.
    
- Case: reading file failed
    
    Expected: should return invalid file with returned error from `ReadFileContent`
    
- Case: parsing YAML failed
    
    Expected: should return invalid file with returned error from `ParseYaml`
    
- Case: success
    
    Expected: should return expected configurations, absolute path and nil
    

**“How to” implementation suggestions**

For `ToAbsolutePath`, the test cases are already exists. Use them by moving `TestToAbsolutePath` to the new `extractor_test` file (find, `TestToAbsolutePath` in `bl/files`).

For `ExtractConfigurationsFromYamlFile` tests

**Requirements**
Golang basic level.

**Comment by sourikghosh** [comment]
I would love to work on this
/assign
