### ISSUE TITLE
Add "How To Fix" guide link

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#446]
**Describe the solution you'd like**

We want to provide an easy way to view guidance on how to fix failing rules. For that, we want to add to the test command output a how-to-fix guidelines link next to every failing rule.

Since this is optional, we want this option to be a flag of test command or as a local configuration. 

```bash
datree test ~/.datree/k8s-demo.yaml --verbose
```

To maintain backward compatibility the links for every rule will be local.

**“How to Implement” suggestion**

1. Create a new package for policies `src/pkg/policy`
    
    This package will include aYAMLl file named `rules`. This file should hold a key-value pair of  all the built-in rules we have in the docs (https://hub.datree.io/built-in-rules)](https://hub.datree.io/built-in-rules). For example:
    
    ```yaml
    CONTAINERS_MISSING_IMAGE_VALUE_VERSION: "https://hub.datree.io/ensure-image-pinned-version"
    ```
    
2. For each rule add the link according to the rule identifier. see `parseToPrinterWarnings`
3. pass verbose option to `PrintResults` → `printer.PrintWarnings` and print link accordingly. 

**Requirements**
Golang intermediate level.

**Comment by AreebAbdulGhani** [comment]
I'm not able to run Datree after installing it in windows
![dt](https://user-images.githubusercontent.com/92576221/156147414-f80cd0c8-eb4f-4e9e-869d-d9e5a65720d9.png)

**Comment by adifayer** [comment]
@AreebAbdulGhani Seems like a possible bug, would you like to open an issue to fix this one?
Also, I'd love to invite you to Datree's [Slack channel](https://datreecommunity.slack.com/archives/C02L0QB3YTC), you can post the issue there as well and the community can assist with this one 🙌
