### ISSUE TITLE
warning: `kIOMasterPortDefault` is deprecated

### ISSUE THREAD

**Issue by amustaque97** [datreeio/datree#512]
When we build our project on macbook intel devices. It shows the following error:

```console
go build -tags staging -ldflags="-X github.com/datreeio/datree/cmd.CliVersion=0.0.1"
# github.com/shirou/gopsutil/host
smc_darwin.c:75:41: warning: 'kIOMasterPortDefault' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:123:19: note: 'kIOMasterPortDefault' has been explicitly marked deprecated here
```

Warning is coming from `gopsutil` package and we're using it here
https://github.com/datreeio/datree/blob/main/bl/evaluation/osInfo.go#L3

I checked `gopsutil` package and found, they have merged their [fix](https://github.com/shirou/gopsutil/pull/1191) . Now we should update package in order to get rid of this warning. 

UPDATE: Sorry I checked again `gopsutil` latest version is [3.21.11](https://pkg.go.dev/github.com/shirou/gopsutil?tab=versions) and fix will be available in 3.22 version. Will have to wait until next release.

**Comment by royhadad** [comment]
thanks for letting us know!
Seems like we'll just need to wait for the next release and this issue will be fixed automatically.
For the meantime, I left them a comment on the pr: https://github.com/shirou/gopsutil/pull/1191#issuecomment-1073843491

**Comment by shirou** [comment]
[v3.22.1](https://github.com/shirou/gopsutil/releases/tag/v3.22.1) and [v3.22.2](https://github.com/shirou/gopsutil/releases/tag/v3.22.2) have already released.

**Comment by royhadad** [comment]
Seems like we need to upgrade our gopsutil package to V3, this is up for grabs :)
We currently use this: https://pkg.go.dev/github.com/shirou/gopsutil/host
We need to upgrade to this: https://pkg.go.dev/github.com/shirou/gopsutil/v3/host
