### ISSUE TITLE
Verify the content of the file received in datree test policy-config flag

### ISSUE THREAD

**Issue by Ben-Zaad** [datreeio/datree#519]
**Describe the solution you'd like**
One of the flags of the datree test command is policy-config, we are currently validating the types of the received policies file with a jsonSchema validation.
Some of the validation logic is not covered by only using jsonSchema so we want to further verify the content of this file by adding validation in our code for:

1. Identifier: 
   a. verify each rule has a unique identifier
   b. verify that each identifier has a corresponding rule to run against
2. verify that exactly 1 policy has it's isDefault value set to true
3. jsonSchema field - verify that the schema is valid
4. schema field - verify that the schema is valid

**Comment by Abhra303** [comment]
Hey @Ben-Zaad, I am interested in this issue. Could you please tell me what you are actually referring to by saying `jsonSchema field` and `schema field`?

Thanks :)

**Comment by Ben-Zaad** [comment]
Hey @Abhra303 :)

when users run datree test with policy-config flag on, they upload a policies.yml file, this file is being validated with [datree](https://github.com/datreeio/datree)/[pkg](https://github.com/datreeio/datree/tree/main/pkg)/[policy](https://github.com/datreeio/datree/tree/main/pkg/policy)/policiesSchema.json json schema file.
on this file, under customRules, we are allowing users to pass "jsonSchema" and "schema" keys, both are currently not being validated.

Gl Hf!

**Comment by Abhra303** [comment]
Got it! Thanks! Will work on it ☺️😊

**Comment by adifayer** [comment]
@Abhra303 You got it 🙌
