### ISSUE TITLE
Test defaultRules.yaml file structure

### ISSUE THREAD

**Issue by royhadad** [datreeio/datree#533]
**Is your feature request related to a problem? Please describe.**
We have a file pkg/policy/defaultRules.yaml - which is the source of truth for the default rules in users' policies.
It's very important we don't break it, therefore - better testing is required.
A quick win would be to test and validate the structure of the yaml

**Describe the solution you'd like**
Add a test file **pkg/policy/defaultRules_test.go** to test the structure of the yaml file.
**Few options here:**
1. Use a yaml-schema - pkg/jsonSchemaValidator/validator.go `ValidateYamlSchema()`
2. Convert it to json and validate using json schema
3. Parse it into a struct and validate it using code
4. A combination of both methods

**What do we want to validate?**
1. the yaml is a non-empty, non-null array
2. validate that the array contains all id's from 1 to 44 (we need this for backwards compatibility)
3. for every item in the array, it is a non-null object with the following keys:
5. id: integer, unique, bigger then 0
6. name: string, unique, not empty
7. uniqueName: string, non-empty, contains only Alphanumerical characters and underscores
8. enabledByDefault: boolean
9. documentationUrl: non empty string
10. messageOnFailure: non empty string
11. category: one of the following: 
`'Containers',
'Workload',
'CronJob',
'Networking',
'Deprecation',
'Security',
'Other',
'Custom',
'Argo'`
12. schema: non-null object. (optional - validate that it's a valid json-schema)

**Describe alternatives you've considered**
Open for suggestions for changes/additions

**Comment by naorpeled** [comment]
Hey,
can you assign me to this issue? :)

**Comment by royhadad** [comment]
@naorpeled sure, there you go 💪
