### ISSUE TITLE
new built-in rule to verify `metadata.name` exists

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#542]
**Is your feature request related to a problem? Please describe.**
`metadata.name` OR `metadata.generateName` is a mandatory property in every K8s resource type.
This validation (that the property exists) is happening on the K8s server-side only (not part of the official schema).
Therefore, if a YAML is passed to datree w/o the mentioned property, it will pass the schema validation but will fail K8s deployment (`kubectl apply/create`)

**Describe the solution you'd like**
Add a new built-in rule (enabled by default) that will verify the property is exist during the policy step. 

**Additional context**
![image](https://user-images.githubusercontent.com/19731161/160866588-802f7740-1782-41c4-a0ba-3cd31103f4ba.png)

**Comment by hadar-co** [comment]
Done.
