### ISSUE TITLE
Bump golang to v1.18

### ISSUE THREAD

**Issue by dimabru** [datreeio/datree#574]
**Is your feature request related to a problem? Please describe.**
We need to stay up to date with golang versions.
Failing to do so will cause us to be behind homebrew build version (which they keep up to date) and can potentially fail future versions from being deployed on homebrew

**Describe the solution you'd like**
Support golang v1.18 :)

**Comment by royhadad** [comment]
generics 😍😍

**Comment by amustaque97** [comment]
Hi there, I would love to work on this issue. 🙂

**Comment by royhadad** [comment]
@amustaque97 Awesome! I've assigned you 😎
