### ISSUE TITLE
Add supported output formats to cli help text

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#586]
**Report type**
Missing documentation
 
**What can be improved?**  
When running `datree test -h` we get the following output:
```
Flags:
  -o, --output string                 Define output format
```

**Suggested solution**  
Add supported formats to help text (json, yaml, xml, JUnit)

**Comment by royhadad** [comment]
fix: (simple, yaml, json, xml, JUnit)

**Comment by eyarz** [comment]
thank you, stale-bot, for reminding us to close to issue :)

**Comment by royhadad** [comment]
@eyarz why close this? there is still a PR open for the issue🤔

**Comment by eyarz** [comment]
oops... my bad.
