### ISSUE TITLE
Can't connect to datree web interface

### ISSUE THREAD

**Issue by Davincible** [datreeio/datree#615]
I have the token set, but whenever I login to the web interface, I only see the 3 step "Running Datree CLI" popup, which won't go away. So I suspect my account is not linking.

How can I fix this?

running the latest version on Manjaro

**Comment by royhadad** [comment]
Did you follow the 3 steps described in the pop-up?

**Comment by Davincible** [comment]
Oui, multiple times. I think my cli datree is not connecting to the server (correctly), but I am not sure how to troubleshoot.

Edit:
Also, whenever I click the link it says "session not valid anymore", but if I'm logged in, it just redirects to my account, showing the popup

**Comment by royhadad** [comment]
would you like to discuss it further on slack and troubleshoot together?
community slack channel:
https://bit.ly/3BHwCEG

**Comment by Davincible** [comment]
Turns out I had installed an old version (0.15.0-1) through pacman, removing that version fixed it.

**Comment by eyarz** [comment]
@Davincible can you give a link to Datree on pacman so we can ask to update the version there?

**Comment by Davincible** [comment]
@eyarz 
https://archlinux.org/packages/community/x86_64/datree/

I noticed that the version just recently got [bumped](https://github.com/archlinux/svntogit-community/blob/packages/datree/trunk/PKGBUILD) up, didn't propagate for me yet

**Comment by eyarz** [comment]
Thanks for the update.
I also reached out to the package maintainer (@shibumi) to explain how to bump the version.
