### ISSUE TITLE
Can you add on-premise version?

### ISSUE THREAD

**Issue by eranhermush** [datreeio/datree#619]
Hi,
The company I work for has a private cloud, and we want to use Datree.
Based on our experience with Kubernetes, we love your product and will be happy to use it in our system.

Thank you very much 😀

**Comment by eyarz** [comment]
This option is already supported! 
We are just in the final steps of testing it with our beta group, and we will add it to our docs :)

I will keep this issue open for now, and I will update here once we have everything tested and documented.
If you (or someone else) also want to try it before the "official" release, ping me and I will send you the info 🤓

**Comment by eyarz** [comment]
docs are ready :)
https://hub.datree.io/setup/offline-mode
