### ISSUE TITLE
Installing the helm plugin on an M1 macbook installs the x86 version instead of the ARM one

### ISSUE THREAD

**Issue by dorongutman** [datreeio/datree#634]
**Describe the bug**
Installing the helm plugin on an M1 macbook installs the x86 version instead of the ARM one

**To Reproduce**
1. Run command `helm plugin install https://github.com/datreeio/helm-datree`
2. See the following: 
```
Installing helm-datree...
https://github.com/datreeio/datree/releases/download/1.4.22/datree-cli_1.4.22_Darwin_x86_64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7442k  100 7442k    0     0  1161k      0  0:00:06  0:00:06 --:--:-- 1347k
helm-datree is installed.

See https://hub.datree.io for help getting started.
Installed plugin: datree
```
3. Notice file name is datree-cli_1.4.22_Darwin_x86_64.zip and not datree-cli_1.4.22_Darwin_arm64.zip

**Expected behavior**
I expect it to install the arm64 version and not the x86_64

**Desktop (please complete the following information):**
 - OS: macOS 12.3.1

**Datree version (run `datree version`):**
 - Version: 1.4.22

**Client ID (`cat ~/.datree/config.yaml`):**
 - N/A

**Additional context**  
Here's the output of running `file $(which helm)` to prove I'm running the arm version of helm:
`/opt/homebrew/bin/helm: Mach-O 64-bit executable arm64`

**Comment by myishay** [comment]
@dorongutman We have merged a fix now. Can you please check if it works on your end?

**Comment by dorongutman** [comment]
@myishay I ran `helm plugin update datree` and indeed it updated to the arm version correctly:
```
Installing helm-datree...
https://github.com/datreeio/datree/releases/download/1.4.26/datree-cli_1.4.26_Darwin_arm64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 7157k  100 7157k    0     0  5005k      0  0:00:01  0:00:01 --:--:-- 13.4M
helm-datree is installed.

See https://hub.datree.io for help getting started.
Updated plugin: datree
```


Thank you!
Closing.
