### ISSUE TITLE
Support UTF-8 Character Set Only

### ISSUE THREAD

**Issue by BlythMeister** [datreeio/datree#646]
When running datree as part of our pipeline with Octopus deploy our output prints as follows:

![image](https://user-images.githubusercontent.com/1046836/170690959-091ebd7e-252d-4730-82eb-5080fcaa6d5e.png)

the same output in a command window on the machine is as follows:

![image](https://user-images.githubusercontent.com/1046836/170691347-8ae13265-f173-4f99-a4dc-3d04ff929634.png)

It would appear that the `—` is not a UTF-8 character and nore are characters in the table (for example the quotes are `“` and `”` rather than `"`

It would be nice if the character set on the simple output was UTF-8 to ensure full compatibility

**Comment by eyarz** [comment]
Those quotation marks (`”`) are sneaky! I didn't notice it's not the regular ones (`"`)... 
@BlythMeister which image/OS you're running on your Octopus deploy machine?
Is this happening with or w/o the `--output simple` flag?

**Comment by BlythMeister** [comment]
It's windows server 2019 and yes it's with simple mode.

The dash seems to be a double length dash too 

I've got no idea what's up with the table though

**Comment by BlythMeister** [comment]
@myishay i had started working on this before you were assigned.
i raised a PR with updates to the characters used which should resolve these issues.

The changes are to use UTF-8 safe characters, rather than Unicode characters.
Also, it seems that the table creation code which is brought in doesn't handle the colour being `Reset` so i've changed it to just do a plain append row when output is `Simple`

**Comment by myishay** [comment]
@BlythMeister Thank you for your contribution! 
We will review it as soon as possible. Let's continue the discussion in the PR's comments
