### ISSUE TITLE
Write policy check results to local log file

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#647]
Background:
1. Github provides an option to [add a job summary within workflows](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) for a nice stylized output. We would like to implement this within our github action.
2. Writing policy check results to a log file will allow us to understand and debug issues more easily.

Solution:
Each "datree test" invocation will write its output to a log file (in JSON format) in addition to the output displayed in the CLI.
The log files will reside in an OS temp folder where they will be deleted periodically.

Our github action will read this log file to extract details of the policy check (num of failed rules, num of files scanned, etc.) and use them in the job summary.

**Comment by amustaque97** [comment]
I think we can use `enable logging` in case of failure in the pipeline https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/

Let me know what do you think?

**Comment by alonzyl** [comment]
I would be happy to help on this issue. Could you please clarify the following points for me?

- Will the file be saved only during the datree test call in the CLI, or will it also be saved during periodic scans?
- Would you like the temporary folder to be automatically deleted after approximately 24 hours, or only the next time the function is called to check for an old file and delete it?
- Where do you want to save the file?

**Comment by hadar-co** [comment]
Hey @alonzyl:) Thanks for picking this up!

Some clarifications:
* For now, this should be supported only in the CLI, not in the periodic scans.
* The solution should be a new flag `--save-results` followed by a path in which to place the results, for example:
  `datree test testFile.yaml --save-results '/path/to/save/in.json'`
* If this flag is set, a JSON file will be saved in the provided location.
* If the flag is used but a path is not provided or is invalid, the CLI should fail with a proper error message.
* The file should not be deleted by us. Since the user chooses where to place it, he will manage its deletion.

If you have any other questions, feel free to ask us 👍
