### ISSUE TITLE
Support "Soft" failure

### ISSUE THREAD

**Issue by BlythMeister** [datreeio/datree#649]
When running checks, have a way to set a rule as a soft failure rule.

This will flag as a warning in the output, but will be identifyable.

The result being you can check the exit code and tell if it ran with all success, soft warnings only, hard failures.

Soft failure would for example allow pipeline to proceed as it's more a warning "you might want to set this up"

**Comment by eyarz** [comment]
🤔  
@BlythMeister but if I set soft fail and my CI will not fail, how will know there is a failure to check/fix?
BTW, we do support [rule skipping](https://hub.datree.io/setup/policy-customization#rule-skipping) on files.

**Comment by BlythMeister** [comment]
For our use case, we report on warnings and have a threshold of warnings.
So X number of warnings causes an error.

**Comment by eyarz** [comment]
This is an interesting use case!
So maybe the `enhancement` should be to create a "warning scoring" (place holder name 😅) mechanism that if passed a threshold, will raise an exit code?

**Comment by BlythMeister** [comment]
I do wonder if the rules could just be silenced for a specific project.
For example if one particular deployment doesn't need a specific label we could just say that it is an ignored rule.

That then means we won't have the failures.

I actually think my usecase is less important 🤣

**Comment by eyarz** [comment]
I think that explicitly ignoring a rule in a specific project is much better than a warning.
from my experience, no one ever fixes a build if it doesn't break. 
this is why we are "missing" this capability 😉

**Comment by BlythMeister** [comment]
Agreed.  Happy to close this issue as "not-required" 👍
