### ISSUE TITLE
Race Condition On Publish Config As Code

### ISSUE THREAD

**Issue by BlythMeister** [datreeio/datree#675]
**Describe the bug**
If during the publish operation another task/build/deploy runs a check it gets a policy with 0 enabled rules.
This happens if you have a shared policy used by multiple different systems

**To Reproduce**
1. Run command 'publish  yamlFile.yaml' & 'test' at the exact same time
2. The test will have no rules

**Expected behavior**
Blocking/Use previous version of published rules

**Screenshots**
![image](https://user-images.githubusercontent.com/1046836/172824888-f526d09c-0fe0-48f8-bfb7-3ce09c84b221.png)

**Desktop (please complete the following information):**
 - OS: Windows

**Datree version (run `datree version`):**
 - Version: 1.5.3

**Comment by myishay** [comment]
Hey @BlythMeister !

I didn't manage to reproduce this yet to be honest. Is this happening constantly?

**Comment by BlythMeister** [comment]
No, I've only seen it once.
It was as though one deployment conflicted with another.

With 1 uploading the policy at the exact same time as another was running.

On the server side when policies are updated and downloaded, if there potential for a race condition there?

I'm not sure if the server side code is open or closed source.

**Comment by myishay** [comment]
The server side is indeed closed source. In a quick look I didn't find any potential race condition but I will have a closer look and let you know.

**Comment by myishay** [comment]
I took a closer look and didn't find any potential race condition to be honest, and with no possible steps to reproduce it will be extremely hard to trace this, so I'll close this issue for now.

@BlythMeister you can reopen this issue with further information if you manage to reproduce. Thanks again!
