### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mkarjun** [datreeio/datree#679]
I'm new to Datree and k8s ,trying to learn, while trying to install to Datree after the step `iwr -useb https://get.datree.io/windows_install.ps1 | iex` it doesnt seems to install .

**- **After Installation [it is Write-Host part]****
 
 `Installing Datree...

[V] Downloaded Datree
[V] Finished Installation

To run datree globally, please follow these steps:

    1. Run the following command as administrator: `setx PATH "$env:path;C:\Users\mkarj\AppData\Local\datree" -m`

    2. Close and reopen your terminal.

For more information, please visit https://datree.io

    Usage: datree test $home/.datree/k8s-demo.yaml

    Run 'datree completion -h' to learn how to generate shell autocompletions`

**- While testing Datree**

`datree : The term 'datree' is not recognized as the name of a cmdlet, function, script file, or operable program. 
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ datree completion -h
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (datree:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException`

Can someone please help to resolve the issue, thank you for your time and consideration.

**Comment by eyarz** [comment]
@mkarjun did you follow the two steps?

> To run datree globally, please follow these steps:
> 1. Run the following command as administrator: `setx PATH "$env:path;C:\Users\mkarj\AppData\Local\datree" -m`
> 2. Close and reopen your terminal.

**Comment by mkarjun** [comment]
@eyarz yes I did follow that step,still it was the same error.
Is it because any configuration i should do in windows side?

By following the steps I was able to install datree in Docker and vm.

**Comment by eyarz** [comment]
🤔
let's continue this support issue [on slack](https://bit.ly/3BHwCEG).
you can PM me directly and I will help you :)

**Comment by mkarjun** [comment]
Thanks @eyarz  : )

**Comment by mkarjun** [comment]
Thanks for your help @eyarz  : ) ,it worked by setting environment variable path through GUI .
closing the issue.
