### ISSUE TITLE
VS extension (Date version : 1.5.9) won't produce proper report on ubuntu22.04 vs code version 1.68

### ISSUE THREAD

**Issue by Pickacho** [datreeio/datree#686]
**Describe the bug**
After running "Run analysis" I get pop-up windows from vs-code which show the the following out put:
_"{"policyValidationResults":null,"policySummary":{"policyName":"Default","totalRulesInPolicy":21,"totalSkippedRules":0,"totalRulesFailed":0,"totalPassedCount":21},"evaluationSummary":{"configsCount":1,"filesCount":1,"passedYamlValidationCount":1,"k8sValidation":"1/1","passedPolicyValidationCount":1},"yamlValidationResults":null,"k8sValidationResults":null}"_

**To Reproduce**
1. ubuntu22.04, vs code version 1.68 , VS extension (Date version : 1.5.9)
2. Click on 'Run analysis'
3. See error

**Expected behavior**
**![Screenshot from 2022-06-14 15-01-40](https://user-images.githubusercontent.com/40912416/173572404-872dba9b-176f-451f-9df5-7ded8c100248.png)**
suppose to show the report in next tab

**Screenshots**
![Screenshot from 2022-06-14 14-56-23](https://user-images.githubusercontent.com/40912416/173573075-ad7b727e-5c5a-4c30-8101-423c292dd897.png)
![Screenshot from 2022-06-14 14-57-58](https://user-images.githubusercontent.com/40912416/173573093-f657d9e2-6fbb-419f-9e51-ddf49a93df4b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu22.04

**Datree version (run `datree version`):**
 - Version: 1.5.9

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: XJ4QPNbUJaKEgqRHR9fS5f

**Comment by adifayer** [comment]
@Pickacho As an open-source, datree has multiple integrations created by the community which aren't supported by our team. this is one of them :)

Here's a link to the extension repository - https://github.com/SuyashSonawane/vscode-datree (@SuyashSonawane is the maintainer of this repo)

**Comment by Pickacho** [comment]
> @Pickacho As an open-source, datree has multiple integrations created by the community which aren't supported by our team. this is one of them :)
> 
> Here's a link to the extension repository - https://github.com/SuyashSonawane/vscode-datree (@SuyashSonawane is the maintainer of this repo)

Thank you @adifay :)
