### ISSUE TITLE
Update the architecture image

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#688]
**Is your feature request related to a problem? Please describe.**
Now that Datree is also supporting a webhook admission controller we need 

**Describe the solution you'd like**
Update the architecture image

**Additional context**
https://github.com/datreeio/datree/blob/main/images/datree_architecture_light.png

**Comment by eyarz** [comment]
@noaabarki any update on this?

**Comment by noaabarki** [comment]
I'm on it :)

**Comment by eyarz** [comment]
https://github.com/datreeio/datree/pull/710
