### ISSUE TITLE
Datree not working in our Air-Gapped environment 

### ISSUE THREAD

**Issue by itaispiegel** [datreeio/datree#702]
**Describe the bug**
We're trying to integrate Datree (version 1.5.20) in our Air-Gapped development cycle, and unfortunately it doesn't work due to a certificate issue.
I of course ran `datree config set offline local`, and I'm still getting a certificate issue when trying to validate https://gateway.datree.io.
First of all - why is it trying to access the external host if I configured it to work offline?
Second, there's no option to configure it to skip this, so unfortunately it doesn't work at all.
I tried to add to my `/etc/hosts` the line `127.0.0.1 gateway.datree.io` and it still failed with the same error.

**To Reproduce**
`datree test ...` (even when runned with `--no-error`.

**Desktop (please complete the following information):**
 - Centos 7.5.1804

**Datree version (run `datree version`):**
 - 1.5.20

**Additional contex**
My YAML file is as following:
```yaml
client_id: (some random id)
offline: local
token: local
```

**Comment by shalev007** [comment]
Hey @itaispiegel,
the `offline` configuration only applies to what happens when there's no internet connection,
for example:
`offline: error` - will throw an error when no connection is established
`offline: local` - will run datree as specified in the documentation [link to doc](https://hub.datree.io/setup/offline-mode
)

regardless we still consider it as a bug since you actually have an air-gapped environment and datree doesn't run as desired,
we're on it and we'll update you soon 👍

**Comment by itaispiegel** [comment]
Great! :)

**Comment by itaispiegel** [comment]
By the way, it might be important to note that in our network, we configured the ingress controller to operate on the wildcard *.io, which is exactly the DNS zone of your server.
Perhaps the bug is caused because this host is resolved to an IP in our environment?

**Comment by myishay** [comment]
Hi @itaispiegel , we are still investigating and trying to solve this issue. I believe that this is related to the way we handle network errors in general.

**Comment by myishay** [comment]
Hi @itaispiegel, we released the fix that will probably solve your issue!
you can find it in [version 1.5.25](https://github.com/datreeio/datree/releases/tag/1.5.25) 
We would love to hear your feedback and see if it worked!

**Comment by itaispiegel** [comment]
@myishay Thanks man! Much appreciated :)

**Comment by myishay** [comment]
@itaispiegel My pleasure! Did it work?

**Comment by itaispiegel** [comment]
@myishay My teammates are currently on this, so I'll let you know once they update me :)

**Comment by itaispiegel** [comment]
Hey, sorry for updating you only now.
It's working. Thanks again :)

**Comment by myishay** [comment]
> Hey, sorry for updating you only now. It's working. Thanks again :)

No worries, thanks for the update!
