### ISSUE TITLE
Disable CLI spinner in CI

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#717]
In github actions and other CI platforms, the "Loading..." spinner is displayed poorly in the output:
![Screen Shot 2022-07-12 at 11 49 07](https://user-images.githubusercontent.com/96784606/178450341-4a6a9599-f2d2-4965-933f-4ddc808ce078.png)

**Describe the solution you'd like**
When running in CI - disable the spinner entirely.

**Describe alternatives you've considered**
When running in CI - use the "-o simple" flag.
I think this is a bad solution, since we don't want to force simple output on users, they might want emojis and colors.

**Comment by eyarz** [comment]
duplicate https://github.com/datreeio/datree/issues/620
