### ISSUE TITLE
Corruption on simultanous calls to set config token

### ISSUE THREAD

**Issue by BlythMeister** [datreeio/datree#725]
**Describe the bug**
Multiple simultanious calls to set token result in a corrupt yaml file

**To Reproduce**
1. Run `config set token` multiple times at the exact same time.
2. Review the config file output
3. There is a chance (not garentee) of corruption

**Expected behavior**
Locking over access to write configuration to allow multi threading to not corrupt the config file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows

**Datree version (run `datree version`):**
 - Version: 1.5.30

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: [e.g. C5fiX5Tm4SvxwkcfXVSHu5]

**Additional context**  
If possible, include a YAML file to reproduce the bug.

**Comment by amustaque97** [comment]
I can probably take a look at this issue if no one is working on it

**Comment by myishay** [comment]
@amustaque97 go for it 🚀🚀

**Comment by amustaque97** [comment]
How are you executing simultaneously calls? I’m assuming these are different processes invocations. Example running command every time in  separate shell instance. If that is the case I don’t think we can control it. Inter process communication is hard to handle. If it would be some threading then it’s a different case. 
cc @BlythMeister @myishay

**Comment by BlythMeister** [comment]
Yes it is.

I'm a c# Dev, in c# I would use mutex to control access to a file system to prevent simultaneous write (or something built into the system IO)

it seems like go does have support for mutex.
I wonder if the set config cli tasks could use a mutex for locking.  A mutex is a system wide lock which will mean only 1 instance of the tool can write at any one time.

**Comment by amustaque97** [comment]
I agree mutex is present in golang std lib. It fails to fix the issue if there are different program execution processes. Mutex is per-process based AFAIK

**Comment by BlythMeister** [comment]
No a mutex is a system lock.

In c# this is done by creating a file on disk and using it to signify the lock in is place.
Other methods can also be used.

But from my research on mutex in go.
These are not process, but system locks.

**Comment by BlythMeister** [comment]
Though the existence of https://github.com/alexflint/go-filemutex library seems to hint otherwise....

But a simple "lock" file approach like git uses when writing config file will suffice really to prevent simultaneous writes.

**Comment by amustaque97** [comment]
Here is an issue on those [lines](https://github.com/golang/go/issues/41912)

Datree is using a package to write config file called ‘viper’ and we cannot modify 3rd party package ‘viper’ even if we follow [this](https://github.com/golang/go/issues/33974)

**Comment by BlythMeister** [comment]
I have managed to work around this as my callers to datree is powershell so I can muted lock there instead.

https://github.com/15below/Ensconce/blob/develop/src/Scripts/kubernetesHelper.ps1#L82-L111

**Comment by myishay** [comment]
@amustaque97 As you mentioned, it seems like there isn't an easy use for mutex in go currently, and since @BlythMeister managed to make a workaround, I will close this issue for now. If you find any solutions for this problem feel free to reopen and comment here. Cheers!
