### ISSUE TITLE
Ignore policy violation via inline comment annotation in yaml file

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/datree#726]
## Problem

There are situations where you may need to locally ignore a single occurrence of a policy rule that you otherwise want applied to all other occurrences.

An example of this is a readiness probe for a product that doesn't have a healthcheck endpoint or that you need to access during bootup UI, such as TeamCity CI Server:

```
>>  File: teamcity-server.yaml

[V] YAML validation
[V] Kubernetes schema validation

[X] Policy check

[X]  Ensure each container has a configured readiness probe  [1 occurrence]
    - metadata.name: teamcity-server (kind: StatefulSet)
[*]  Missing property object `readinessProbe` - add a properly configured readinessProbe to notify kubelet your Pods are ready for traffic
```

The YAML this was raised from contains a detailed explanation of why a readinessProbe is not applied in this case:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/teamcity/base/teamcity-server.yaml#L86

## Proposed Solution

I'd like the ability to add an inline comment annotation to ignore the next occurrance of this rule violation. This is something that most linting tools already support, so it's a well-known solution for this use case.

Example: to ignore just this one occurrence of this policy rule violation, add a comment just before it like this:

```
# datree: ignore=<rule-name-1>,<rule-name-2>,...
#readinessProbe:
#   commented out stuff
```

This should apply only to the current container / next violation from where this comment annotation is found.

If found at the top of the file before any non-comment/blank lines then it should apply to all occurrences of the rule violation in the file.

**Describe alternatives you've considered**

Disabling this check in the policy, but this would apply to all files and I want it to apply to all other occurrences as usually missing a readinessProbe is a real mistake.

**Comment by adifayer** [comment]
Hey @HariSekhon,
We support skipping rules per resource by adding an annotation to the manifest of the resource, here's a link to our docs: https://hub.datree.io/setup/policy-customization
Does that solve your problem?😊

**Comment by HariSekhon** [comment]
Ah yes that should solve it thanks.

I had a look through the docs but missed that page... perhaps there should be reference to this in Centralized Policy as an override section or link?

I even googled for `datree ignore rule comment` but didn't get a hit on this.

Perhaps it needs some SEO and/or cross-doc links?

**Comment by adifayer** [comment]
@HariSekhon Interesting! I agree with you that it's worthwhile to make this page surface more.
I suspect that the issue originates in the name of that page (currently Policy customization). Maybe it will be more intuitive if the name is more specific, something like "Skip/ignore rules"? 
Also, did you also run a search within the docs? and if so, do you recall what terms you searched for?

**Comment by HariSekhon** [comment]
I didn't, as I didn't notice the search bar at the top right, but have just tried with a range of terms like `ignore`, `rule`, `ignore comment`, `ignore rule` and didn't get a hit.

Improving the page title should help get a hit on it.

**Comment by HariSekhon** [comment]
Looks like I've found a problem with the annotations based ignore approach:

```shell
$ datree test service.nodeport.patch.yaml

>>  File: /Users/hari/github/k8s/service.nodeport.patch.yaml

[V] YAML validation
[X] Kubernetes schema validation

[X]  k8s schema validation error: For field metadata: Additional property annotation is not allowed
```

Looks like not all objects can take the annotation in their spec, like this, so the rule triggers on this file but I can't ignore it:

https://github.com/HariSekhon/Kubernetes-configs/blob/master/service.nodeport.patch.yaml

I think this is why the comment-based ignore rules are safer when it comes to file linting, but I appreciate the annotations would be more useful for live governance.

Perhaps support could be added for both styles to solve this problem?

**Comment by eyarz** [comment]
Interesting 🤔
According to the [K8s docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#attaching-metadata-to-objects), all object types support the `annotations` property.

when I'm trying to reproduce it on object type `Service`, I'm **not getting the same schema error** that you're getting:
![image](https://user-images.githubusercontent.com/19731161/179559672-a0433ba1-7227-4c5f-8abf-901573fb53ab.png)

**Comment by HariSekhon** [comment]
Ah, please ignore, this was my fault, `annotation` instead of `annotations` (was end of the day I must have been tired).
