### ISSUE TITLE
Datree outage?

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/datree#727]
Is there a Datree outage?

```shell
$ datree test teamcity-server.yaml
Failed since internet connection refused, you can use the following command to set your config to run offline:
datree config set offline local
```

```shell
$ ping google.com
PING google.com (142.250.200.206): 56 data bytes
64 bytes from 142.250.200.206: icmp_seq=0 ttl=113 time=23.566 ms
64 bytes from 142.250.200.206: icmp_seq=1 ttl=113 time=24.522 ms
64 bytes from 142.250.200.206: icmp_seq=2 ttl=113 time=24.886 ms
64 bytes from 142.250.200.206: icmp_seq=3 ttl=113 time=24.259 ms
^C
--- google.com ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 23.566/24.308/24.886/0.483 ms
```

but still:
```shell
$ datree test teamcity-server.yaml
Failed since internet connection refused, you can use the following command to set your config to run offline:
datree config set offline local
```

**Desktop (please complete the following information):**
 - OS: Mac

**Datree version (run `datree version`):**
 - Version: 1.5.30

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: YAT7PdyxWVANePvsXQnPfK

Ful config:
```shell
cat ~/.datree/config.yaml | anonymize.py --all
client_id: YAT7PdyxWVANePvsXQnPfK
offline: fail
token: <token>
```

(`anonymize.py` is from [here](https://github.com/HariSekhon/DevOps-Python-tools))

**Additional context**  
This was working earlier today, so I'm guessing this is an outage?

**Comment by eyarz** [comment]
We had an issue with a query that got stuck while running on our DB to update **some accounts** dashboard.
We already deployed a fix, so it should work fine by now!

**Comment by HariSekhon** [comment]
Yeah it seems to work again now, I had done the recommended `datree config set offline local` as a temporary workaround and by the time I reverted it a while later with `datree config set offline fail` to check the upstream again it seemed to work normally.

I'm not sure where that revert command is documented as I still can't find it at the link below but inferred it from the original config file setting:

https://hub.datree.io/setup/offline-mode#air-gapped-environment-support

**Comment by eyarz** [comment]
You're right!
I opened a new issue on our docs project to document this command (`datree config set offline`).
I'm closing this issue since the bug got fixed.
