### ISSUE TITLE
Idea - Link to datree website on failures

### ISSUE THREAD

**Issue by BlythMeister** [datreeio/datree#740]
**Is your feature request related to a problem? Please describe.**
When you have failures the error message although clear would be nice to include a link to the datree docs which are very rich with useful information

**Describe the solution you'd like**
As part of the failure, include a link to the datree website

**Describe alternatives you've considered**
When doing config as code you can supply your own error message which can include the link

**Comment by adifayer** [comment]
Hey @BlythMeister 🙋‍♀️ Are you familiar with `--verbose` CLI flag? It displays the link to the docs page of each failing rule. Does it solve the problem? :)
<img width="1065" alt="image" src="https://user-images.githubusercontent.com/43816136/180746488-09bd57fe-6238-4ec5-9661-32c9718ce33f.png">

**Comment by BlythMeister** [comment]
ahh yeah that's what i wanted :)
love it when a feature idea already exists.  thanks @adifay 

Works with the simple output too (which we need to use for UTF-8 compat) 
![image](https://user-images.githubusercontent.com/1046836/180747120-02a18dac-21c1-4d47-b979-ef1bd50ed0ac.png)

**Comment by adifayer** [comment]
Awesome! I'm happy to hear @BlythMeister 🤗
