### ISSUE TITLE
Prevent ConfigMap security vulnerability (Incorrect Fail)

### ISSUE THREAD

**Issue by BlythMeister** [datreeio/datree#741]
**Describe the bug**
This rule documents that in order to fail the config map must be for ingress or nginx
However, it will fail on _all_ config maps

Either the documentation is wrong and this does apply to all config maps, or the test is wrong :)

**To Reproduce**
1. Run command 'test' on yaml with a config map
3. See error

**Expected behavior**
Only fail when nginx/ingress config map

**Workaround**
Add `allow-snippet-annotations: "false"` to the data and the rule will pass.

[example.yaml.txt](https://github.com/datreeio/datree/files/9180500/example.yaml.txt)

**Comment by adifayer** [comment]
I was able to reproduce the incorrect failure with the example that you provided @BlythMeister, thanks!
I'm looking into the rule's logic as we speak, will update soon on my findings :)

**Comment by eyarz** [comment]
@BlythMeister we actually [updated this rule](https://github.com/datreeio/datree/issues/703#issuecomment-1179664559) 2 weeks ago to match the behavior you described as expected.
Apparently, the new rule logic was still catching irrelevant ConfigMap objects, so @hadar-co uploaded a fix and it will be updated in the next CLI release.
