### ISSUE TITLE
Support datree upgrade command

### ISSUE THREAD

**Issue by noaabarki** [datreeio/datree#752]
**Describe the solution you'd like**

Add new `upgrade` command to install the latest datree version. 

- The command should support only macOS & Linux.
- The command should check if the user installed Datree with brew and if so, the command should fail and return a message “Looks like you installed Datree via brew, to upgrade datree run - brew upgrade datree”
- The command should not support pinned or user-defined versions.

**Requirements**
Golang mid-level.

**Reference:** [https://github.com/cli/cli/blob/trunk/pkg/cmd/extension/command.go](https://github.com/cli/cli/blob/trunk/pkg/cmd/extension/command.go)

**Comment by amustaque97** [comment]
Hi there, I would love to give it a shot, can you please assign this issue to me?

**Comment by amustaque97** [comment]
Hi there, I just started looking into the issue. One quick question I have is when we upgrade the _datree_ version what is going to be the default path for the new binary?
