### ISSUE TITLE
don't auto-delete rendered manifest (kustomize/helm)

### ISSUE THREAD

**Issue by eyarz** [datreeio/datree#754]
**Is your feature request related to a problem? Please describe.**
Today, when running datree with kustomize or helm, datree is rendering a manifest in the temp file, passes it for scanning, and deletes the rendered files

**Describe the solution you'd like**
for easy debugging, it will be useful if the file will not be deleted 

**Describe alternatives you've considered**
rendering the manifest by myself

**Additional context**
the default behavior is still to delete the file.
* If the user passes the flag `--save-rendered`, the file will not be deleted from the temp dir
* If the user passes the flag `--save-rendered [path]`, the file will be created in %path%

**Comment by hadar-co** [comment]
@eyarz should be one word `--save-rendered`

**Comment by eyarz** [comment]
my bad :) fixed.

**Comment by amustaque97** [comment]
Can we close this issue? or is there any action item required for this? 🤔

**Comment by eyarz** [comment]
@amustaque97 we are waiting for someone to grab this issue.
This wasn't resolved yet.

**Comment by amustaque97** [comment]
> my bad :) fixed.

sorry I got confused because of the above comment from you @eyarz

**Comment by shalev007** [comment]
The framework we use does not allow flags with triple meanings (true, false and %path%)
therefor the flag will only have a boolean value,
as in just `--save-rendered`
and it will save the rendered file to the temp directory

**Comment by eyarz** [comment]
Implemented.
