### ISSUE TITLE
add documentation command

### ISSUE THREAD

**Issue by TzlilSwimmer123** [datreeio/datree#763]
**Is your feature request related to a problem? Please describe.**
An easy way to open datree documentation

**Describe the solution you'd like**
Adding `documentation` or `docs` command that will open a browser with datree documentation

**Comment by Kanika637** [comment]
Hey @TzlilSwimmer123, can you tell me, how we can achieve this?
I want to work on this issue

**Comment by TzlilSwimmer123** [comment]
Hi @Kanika637 

At the moment we have some commands like: `test`, `config`, `publish`. My suggestion is to add a new command that user can use like `datree docs` or `datree documentation` and this command will open datree docs link in the browser. 
The link `https://hub.datree.io/`

**Comment by myishay** [comment]
@Kanika637  We are using [cobra](https://github.com/spf13/cobra) as our commands framework.
We also have an already implemented function `openBrowser` [here](https://github.com/datreeio/datree/blob/main/cmd/test/testCommandHelper.go) that opens a browser with a given url.
So, what you can do is to add a new command under the root command and use the `openBrowser` in this command. Since this function will not be only for test package anymore, it's location could be changed to `pkg/utils` for example and then you can use it both for `test` command and `pkg/utils` command.
WDYT?

**Comment by Kanika637** [comment]
Okay, I got it ! @myishay 
I have to add it in cmd>root.go right?

**Comment by myishay** [comment]
@Kanika637 correct!

The `version` command can be a good hint on how to implement the file structure etc.

**Comment by amustaque97** [comment]
Hi there, looks like there is no active development on this issue. I can take it up.

**Comment by TzlilSwimmer123** [comment]
@Kanika637 it seems like long time passed. You will have time to develop it or we can assign another contributor?

**Comment by imrushi** [comment]
Hi @TzlilSwimmer123, I am working on this issue to see if I can solve it. I have one question: the docs URL will be hardcoded or dynamic? If it is dynamic, from which place will I get the URL?

**Comment by TzlilSwimmer123** [comment]
Hi @imrushi, @amustaque97 wanted this issue, @amustaque97 do you still want it?

**Comment by amustaque97** [comment]
> Hi @imrushi, @amustaque97 wanted this issue, @amustaque97 do you still want it?

Hey @TzlilSwimmer123, I have no issues if @imrushi wants to work on this. Please go ahead 🚀

**Comment by imrushi** [comment]
@TzlilSwimmer123, the docs URL will be hardcoded or dynamic? If it is dynamic, from which place will I get the URL?

**Comment by Kanika637** [comment]
So sorry for the delay, you may assign it to someone else @TzlilSwimmer123.

**Comment by TzlilSwimmer123** [comment]
@imrushi as mentioned above, the URL is: `https://hub.datree.io` 💪

**Comment by TzlilSwimmer123** [comment]
@imrushi how is it going?

**Comment by imrushi** [comment]
Hi @TzlilSwimmer123, I have created PR but there were some changes. So I was stuck at the mocking browser for testing. It took me some time to figure it out. I have resolved it just waiting to get my PR review.
