### ISSUE TITLE
Some CRDs are missing even though they are present in CRD database

### ISSUE THREAD

**Issue by gilbahat** [datreeio/datree#770]
**Describe the bug**
Some CRDs are not picked up by datree even though they exist in CRD database. see attached test case.

➜  my-rabbitmq-resources datree test *.yaml
>>  File: kustomization.yaml

[V] YAML validation
[X] Kubernetes schema validation

❌  k8s schema validation error: could not find schema for Kustomization
You can skip files with missing schemas instead of failing by using the `--ignore-missing-schemas` flag

Are you trying to test Kustomize files? To run Datree with Kustomize, use `datree kustomize test` command, or check out Kustomize support docs:
https://hub.datree.io/kustomize-support

[?] Policy check didn't run for this file

>>  operator.yaml

[V] YAML validation
[X] Kubernetes schema validation

❌  k8s schema validation error: could not find schema for HelmRelease
You can skip files with missing schemas instead of failing by using the `--ignore-missing-schemas` flag

[?] Policy check didn't run for this file

>>  permission-list.yaml

[V] YAML validation
[X] Kubernetes schema validation

❌  k8s schema validation error: could not find schema for PermissionList
You can skip files with missing schemas instead of failing by using the `--ignore-missing-schemas` flag

[?] Policy check didn't run for this file

>>  File: /Users/gilbahat/laminar/my-rabbitmq-resources/user-datadog-creds.yaml

[V] YAML validation
[X] Kubernetes schema validation

❌  k8s schema validation error: could not find schema for SealedSecret
You can skip files with missing schemas instead of failing by using the `--ignore-missing-schemas` flag

[?] Policy check didn't run for this file

(Summary)

- Passing YAML validation: 10/10

- Passing Kubernetes (1.20.0) schema validation: 6/10

- Passing policy check: 6/10

+-----------------------------------+------------------------------------------------------+
| Enabled rules in policy "Default" | 21                                                   |
| Configs tested against policy     | 11                                                   |
| Total rules evaluated             | 126                                                  |
| Total rules skipped               | 0                                                    |
| Total rules failed                | 0                                                    |
| Total rules passed                | 126                                                  |
| See all rules in policy           | <redacted> |
+-----------------------------------+------------------------------------------------------+

**To Reproduce**

1. unpack attached testcase [rabbitmq.tar.gz](https://github.com/datreeio/datree/files/9439388/rabbitmq.tar.gz)
2. run "datree test *.yaml"
3. Observe error messages

**Expected behavior**
YAML files should have been validated using schema present in CRD database
You will note that -some- yamls with custom resource types have been picked up properly by datree.
the original CRDs can be found at https://github.com/rabbitmq/cluster-operator

**Desktop (please complete the following information):**
 - OS: MacOS

**Datree version (run `datree version`):**
 - Version: 1.6.13

**Client ID (`cat ~/.datree/config.yaml`):**
client_id: wqbrsHFuvY5yHqAeiHahnf

**Comment by hadar-co** [comment]
Hi @gilbahat :)

The version of the resource that you're using might not exist in the catalog, perhaps it's there but with a different APIversion?

**Comment by gilbahat** [comment]
I am not sure how to check that, but for one of these CRDs, the schemas were extracted just an hour ago and merged into the DB from this specific reference. That may indicate a problem with the CRD database extractor or the extracted schemas themselves.

(edit: seems to pass too, see here):

➜  my-rabbitmq-resources kubeconform -summary -output json -strict -schema-location default -schema-location ../schemastuff/CRDs-catalog/rabbitmq.com/permission_v1beta1.json -verbose permission-list.yaml
{
  "resources": [
    {
      "filename": "permission-list.yaml",
      "kind": "PermissionList",
      "name": "rabbitmq-permission-list",
      "version": "rabbitmq.com/v1beta1",
      "status": "statusValid",
      "msg": ""
    }
  ],
  "summary": {
    "valid": 1,
    "invalid": 0,
    "errors": 0,
    "skipped": 0
  }
}


As for the other two, when running kubeconform with the explicit schema imported, they are subjected to validation:

➜  my-rabbitmq-resources kubeconform -summary -output json -strict -schema-location default -schema-location ../schemastuff/CRDs-catalog/kustomize.toolkit.fluxcd.io/kustomization_v1beta2.json -verbose kustomization.yaml
{
  "resources": [
    {
      "filename": "kustomization.yaml",
      "kind": "Kustomization",
      "name": "",
      "version": "kustomize.config.k8s.io/v1beta1",
      "status": "statusValid",
      "msg": ""
    }
  ],
  "summary": {
    "valid": 1,
    "invalid": 0,
    "errors": 0,
    "skipped": 0
  }
}
➜  my-rabbitmq-resources kubeconform -summary -output json -strict -schema-location default -verbose kustomization.yaml
{
  "resources": [
    {
      "filename": "kustomization.yaml",
      "kind": "Kustomization",
      "name": "",
      "version": "kustomize.config.k8s.io/v1beta1",
      "status": "statusError",
      "msg": "could not find schema for Kustomization"
    }
  ],
  "summary": {
    "valid": 0,
    "invalid": 0,
    "errors": 1,
    "skipped": 0
  }
}

➜  my-rabbitmq-resources kubeconform -summary -output json -strict -schema-location default -verbose operator.yaml
{
  "resources": [
    {
      "filename": "operator.yaml",
      "kind": "HelmRelease",
      "name": "rabbitmq-cluster-operator",
      "version": "helm.toolkit.fluxcd.io/v2beta1",
      "status": "statusError",
      "msg": "could not find schema for HelmRelease"
    }
  ],
  "summary": {
    "valid": 0,
    "invalid": 0,
    "errors": 1,
    "skipped": 0
  }
}
➜  my-rabbitmq-resources kubeconform -summary -output json -strict -schema-location default -schema-location ../schemastuff/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v1.json -verbose operator.yaml
{
  "resources": [
    {
      "filename": "operator.yaml",
      "kind": "HelmRelease",
      "name": "rabbitmq-cluster-operator",
      "version": "helm.toolkit.fluxcd.io/v2beta1",
      "status": "statusInvalid",
      "msg": "For field spec: Additional property interval is not allowed - For field spec.chart: Additional property spec is not allowed"
    }
  ],
  "summary": {
    "valid": 0,
    "invalid": 1,
    "errors": 0,
    "skipped": 0
  }
}

(this could be a schema mismatch but apparently not one specified in the files?)

**Comment by hadar-co** [comment]
Look at HelmRelease for example, from what you pasted above:

"filename": "operator.yaml",
"kind": "HelmRelease",
"name": "rabbitmq-cluster-operator",
"version": "helm.toolkit.fluxcd.io/v2beta1"

The version specified in your YAML is **v2beta1**, while in the CRD-catalog there is only one schema for HelmRelease but for version **v1**, see here:
https://github.com/datreeio/CRDs-catalog/tree/main/helm.toolkit.fluxcd.io

That is why the schema is not found. You should either add the desired schema to the catalog, or use v1 in your project.
