### ISSUE TITLE
Kustomize doesn't work with docker image

### ISSUE THREAD

**Issue by korjavin** [datreeio/datree#771]
``` run -it --rm -v$PWD:/app datree/datree kustomize test /app/overlays/prod/kustomization.yml /app ```
kubectl or kustomize is not installed

**Comment by adifayer** [comment]
@korjavin The datree/datree image is a lightweight version of Datree that doesn't include the kustomize binary. 
As a fast solution, I suggest that you use [datree/datreeci](https://hub.docker.com/r/datree/datreeci) image that also contains kustomize :)

**Comment by adifayer** [comment]
@korjavin Hey, were you able to solve this one with our datreeci image? Can I close this issue?

**Comment by korjavin** [comment]
Yes, thanks
