### ISSUE TITLE
pre-commit I got an error "mkdir /.datree: permission denied"

### ISSUE THREAD

**Issue by parraletz** [datreeio/datree#779]
**Describe the bug**
When I want to run datree as part of pre-commit I get an error "mkdir /.datree: permission denied"
**To Reproduce**
1. pre-commit run --all-files 
2. See error

<img width="1308" alt="Screen Shot 2022-09-06 at 20 52 32" src="https://user-images.githubusercontent.com/1150748/188771160-69a05718-dbb9-49c6-bcde-86e60c24d34f.png">

**Desktop (please complete the following information):**
 - OS: OSX

**Comment by parraletz** [comment]
I can replicated on ubuntu 20.04
<img width="1087" alt="Screen Shot 2022-09-06 at 22 11 47" src="https://user-images.githubusercontent.com/1150748/188780369-f0966476-e420-4530-939f-3de70385894c.png">

**Comment by royhadad** [comment]
Managed to reproduce it, these are the steps that I had to follow:
1. install the pre-commit framework https://pre-commit.com/#installation
2. add the pre-commit hook to my personal project, datree has 2 kinds of pre-commit hooks, this is the one https://hub.datree.io/integrations/pre-commit-hook
3. run the following `pre-commit run --all-files`
![Screen Shot 2022-09-07 at 14 16 15](https://user-images.githubusercontent.com/39004075/188865441-78c15cf2-b83c-40c3-8910-9d0c756c6589.png)

**Comment by royhadad** [comment]
@parraletz 
Seems that the pre-commit framework implicitly adds a non-root user when running the hook. I fixed it by explicitly passing `--user root` to the pre-commit entrypoint config

**Comment by royhadad** [comment]
if you are using `rev: HEAD` in you *.pre-commit-config.yaml*, just make sure to run `pre-commit autoupdate` to update to the latest version of datree 😀

**Comment by parraletz** [comment]
Nice!

It works!

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/1150748/189233758-d266fa69-ac5b-4e9b-b25f-88592d2407d6.png">
