### ISSUE TITLE
Getting error on Running datree even after installation

### ISSUE THREAD

**Issue by beingtechsavy** [datreeio/datree#788]
Hello everyone,
Recently I downloaded the CLI setup of datree for windows.
I did all the installation and even set the path command given in the tutorial.
Yet I am not able to run 'datree' on the desktop.

**Comment by beingtechsavy** [comment]
Refer to my screenshot!
![Screenshot (57)](https://user-images.githubusercontent.com/111677648/189756421-2c79def2-4a25-4b37-81e8-313649d3ed17.png)

**Comment by beingtechsavy** [comment]
Hello,
So apparently the problem was that I had to setup the path env variable manually since the powershell couldn't do it.
THankyou for support.

**Comment by royhadad** [comment]
@beingtechsavy  Interesting, do you have any idea why the PowerShell command failed to set the path variable?

**Comment by beingtechsavy** [comment]
> 
No Roy,
I tried many times but it didn't run. :)
