### ISSUE TITLE
Policy check fails but it doesn't reflect in the final summary

### ISSUE THREAD

**Issue by kaustubhnerurkar** [datreeio/datree#79]
**Describe the bug**
Let's say I have a deployment file and it has replicas field set to blank for whatever reason. Now when 'datree test' is run on this file, it shows a failed policy but final summary shows 'Total rules failed' as 0.

**To Reproduce**
Steps to reproduce the behaviour:
1. Make a sample Kubernetes Deployment in a yaml and set the 'replicas' field to an empty value
2. Run 'datree test <your yaml file>'
3. Observe the logs. It says 'Ensure Deployment has more than one replica configured [1 occurrences]' under 'Policy Check' but in the final summary at the bottom, you can see 'Total rules failed' as 0.

**Expected behavior**
'Total rules failed' should include the count for this failed check.

**Screenshots**
![image](https://user-images.githubusercontent.com/34393416/124096707-75aaf180-da78-11eb-972a-b444514b4c31.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**
None

**Comment by dimabru** [comment]
Hi @kaustubhnerurkar,
I'm having trouble reproducing this. Can you please share the yaml file you used to produce this output?

Also, can you please add the version you are using? You can do this by running `datree version`

Thanks,
DIma

**Comment by dimabru** [comment]
We deployed a fix that we believe should solve these types of issues in version `0.1.741`.
In case the issue persists please feel free to comment on this thread and reopen this issue.
Closing it for now.

Thanks,
Dima
