### ISSUE TITLE
Add Datree as package in Scoop package manager for Windows users

### ISSUE THREAD

**Issue by pcgeek86** [datreeio/datree#799]
**Is your feature request related to a problem? Please describe.**

- As a Windows user, I manage my dev tools using the Scoop command line package manager.
- I install other tools, such as `kubectl`, `meshery`, `kubeseal`, and others, using Scoop.
- I would like to install Datree CLI using Scoop package manager.

![image](https://user-images.githubusercontent.com/466713/190503930-78603a4e-5fb9-42c8-bd2f-fda81b3270ba.png)

**Describe the solution you'd like**

I would like Datree CLI distributed via Scoop package manager for Windows.

**Describe alternatives you've considered**

n/a

**Additional context**

- [ ] TODO: Create [Scoop package manifest](https://github.com/ScoopInstaller/Main) for Datree CLI.

**Comment by darkknight20032001** [comment]
I am interested.

**Comment by adifayer** [comment]
@darkknight20032001 Would you like to be assigned to this task? :)

**Comment by darkknight20032001** [comment]
> @darkknight20032001 Would you like to be assigned to this task? :)

Yes please

**Comment by adifayer** [comment]
@darkknight20032001 You got it ✨

**Comment by rakshitgondwal** [comment]
Hey! @darkknight20032001. Are you still working on this?

**Comment by aamirpatel** [comment]
hey! @darkknight20032001 would you like to assign me this task?

**Comment by adifayer** [comment]
@aamirpatel the issue is up for grabs, feel free to assign yourself if you'd like that :)

**Comment by SarveshRansubhe** [comment]
datree is now available on [scoop](https://github.com/ScoopInstaller/Main/pull/4525)

**Comment by eyarz** [comment]
@SarveshRansubhe how can we also update the scoop version on every datree new release?
I'm afraid scoop users will not get the most up-to-date version in the future...

**Comment by SarveshRansubhe** [comment]
They have bot which autoupdates as I have specified a "autoupdate" field there.
