### ISSUE TITLE
Unable to view results in an Azure DevOps pipeline

### ISSUE THREAD

**Issue by grafikkaos** [datreeio/datree#81]
**Is your feature request related to a problem? Please describe.**
There are limited output options for Datree.  When used with Azure DevOps, it would be nice to able to pulish the results of these checks

**Describe the solution you'd like**
A JUnit output format would be extremely welcome to make it easier to export the results.  This can then be viewed in the Azure DevOps pipeline.

**Comment by eyarz** [comment]
I researched a little, and it looks like JUnit output for the Azure DevOps pipeline is just a regular XML output format.
Do you know what the structure of this XML should look like for it to be parsed automatically by Azure DevOps pipeline?

**Comment by eyarz** [comment]
done.
