### ISSUE TITLE
The `--only-k8s-files` flag should ignore empty files

### ISSUE THREAD

**Issue by hadar-co** [datreeio/datree#810]
**Is your feature request related to a problem? Please describe.**
When running `datree test --only-k8s-files` on an empty file, the CLI fails in the schema-validation step.

**Describe the solution you'd like**
The CLI should ignore empty files when this flag is passed, as they are not valid k8s files.

**Comment by alonzyl** [comment]
I would like to work on this issue :)

**Comment by hadorco** [comment]
@alonzyl Awesome, thanks 🤟

**Comment by alonzyl** [comment]
Hi,
As I see it, there are two ways to solve the problem. The first one is that when the flag is passed, ValidateResources would not flag it as an error; it will just flag it as valid or skipped K8s files configurations. The other option is that inside GetK8sFiles, it would open the file. However, this does not seem like the best approach.

I would like to get your opinion. Perhaps I am missing something.
