### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by jkevingutierrez** [datreeio/datree#82]
**Is your feature request related to a problem? Please describe.**
Right now Datree  requires that we sign up in order to be able to change policies or default configs.

**Describe the solution you'd like**
It would be great to be able to edit that info having a datree config file that could be comited to repos

**Additional context**
It would be equivalent to files like .eslintrc.yaml or analysis_options.yaml

**Comment by eyarz** [comment]
This a great feature request that we do want to implement!
Can you elaborate more on your use case for that? It will make it easier for us to plan and execute this feature :)
