### ISSUE TITLE
Publish report to local filesystem

### ISSUE THREAD

**Issue by noorul** [datreeio/datree#846]
**Is your feature request related to a problem? Please describe.**
Today there is no option to publish the report to CI system like Jenkins. The only option available is the cloud. See the discussion comment https://github.com/datreeio/datree/discussions/841#discussioncomment-4226275

**Describe the solution you'd like**
Provide an option to publish the report to the local filesystem.

**Describe alternatives you've considered**
We do not want to publish to datree cloud service

**Comment by adifayer** [comment]
@noorul What report do you refer to, do you mean the results of the policy check (CLI output)?
![image](https://user-images.githubusercontent.com/43816136/204282136-2135786d-fbc6-4ac5-859a-18854af2b64a.png)

**Comment by noorul** [comment]
Yes

**Comment by adifayer** [comment]
So the requested feature is to be able to write the CLI output to a local path? If so, it can be achieved by piping datree test result to a local path: `datree test [path] > [local-file-path]` 
Does that solve this one? :) @noorul

**Comment by noorul** [comment]
That is not what I am looking for. Exporting to a more widely used format like HTML.

**Comment by hadar-co** [comment]
@noorul We currently do not support HTML as an option for the output format, but we do support the following: `yaml, json, xml, JUnit, sarif`

To use these, pass the -o option to the CLI followed by your desired output, for example:
`datree test file.yaml -o json`

**Comment by adifayer** [comment]
@noorul  Would you like to have the output of a single policy check in HTML format? I'm not sure I fully understand the use case, why do you want to have it HTML?

**Comment by noorul** [comment]
The use case is to publish the result in Jenkins CI. I think maybe JUnit can be leveraged for this. I am closing this for the time being.
