### ISSUE TITLE
Dashboard login giving error in verifying token.

### ISSUE THREAD

**Issue by Nikhil26112** [datreeio/datree#847]
I tried to login to datree dashboard on https://app.datree.io/webhook-instructions. But I am unable to login to it because an error is coming whenever I run this command: 
```
                helm install -n datree datree-webhook datree-webhook/datree-admission-webhook \
                --create-namespace \
                --set datree.token=5fb***2ac0 \
                --debug
```
this is the output which I am getting : 
```
install.go:178: [debug] Original chart version: ""
install.go:199: [debug] CHART PATH: /home/nikhil/.cache/helm/repository/datree-admission-webhook-0.3.14.tgz

client.go:128: [debug] creating 1 resource(s)
client.go:128: [debug] creating 20 resource(s)
client.go:128: [debug] creating 1 resource(s)
client.go:528: [debug] Watching for changes to Job datree-label-namespaces-hook-post-install with timeout of 5m0s
client.go:556: [debug] Add/Modify event for datree-label-namespaces-hook-post-install: ADDED
client.go:595: [debug] datree-label-namespaces-hook-post-install: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-label-namespaces-hook-post-install: MODIFIED
client.go:595: [debug] datree-label-namespaces-hook-post-install: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-label-namespaces-hook-post-install: MODIFIED
client.go:128: [debug] creating 1 resource(s)
client.go:528: [debug] Watching for changes to Job datree-wait-server-ready-hook-post-install with timeout of 5m0s
client.go:556: [debug] Add/Modify event for datree-wait-server-ready-hook-post-install: ADDED
client.go:595: [debug] datree-wait-server-ready-hook-post-install: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-wait-server-ready-hook-post-install: MODIFIED
client.go:595: [debug] datree-wait-server-ready-hook-post-install: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-wait-server-ready-hook-post-install: MODIFIED
client.go:595: [debug] datree-wait-server-ready-hook-post-install: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-wait-server-ready-hook-post-install: MODIFIED
client.go:595: [debug] datree-wait-server-ready-hook-post-install: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-wait-server-ready-hook-post-install: MODIFIED
client.go:595: [debug] datree-wait-server-ready-hook-post-install: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:556: [debug] Add/Modify event for datree-wait-server-ready-hook-post-install: MODIFIED
client.go:595: [debug] datree-wait-server-ready-hook-post-install: Jobs active: 1, jobs failed: 1, jobs succeeded: 0
client.go:299: [debug] Starting delete for "datree-wait-server-ready-hook-post-install" Job
Error: INSTALLATION FAILED: failed post-install: timed out waiting for the condition
helm.go:88: [debug] failed post-install: timed out waiting for the condition
INSTALLATION FAILED
main.newInstallCmd.func2
	helm.sh/helm/v3/cmd/helm/install.go:127
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.2.1/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.2.1/command.go:974
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.2.1/command.go:902
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:87
runtime.main
	runtime/proc.go:225
runtime.goexit
	runtime/asm_amd64.s:1371
```
![Screenshot from 2022-11-25 16-20-58](https://user-images.githubusercontent.com/72178665/203968620-7ffac4a9-9858-4d6f-8fbb-bb8ca577ccbb.png)

**Expected behavior**
Login to datree dashboard

**Desktop (please complete the following information):**
 - OS: Ubuntu

**Datree version (run `datree version`):**
 - Version: 1.8.1

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: XXaKCoqJSBKNMb3AounaUg

Please help me resolving this issue.
Thank you

**Comment by royhadad** [comment]
@Nikhil26112 
Can you give some more context on the environment you tried to install in?

eks? fargate? minikube? do you have enough cpu/memory?
maybe check for error logs in the deployment resource?

thx

**Comment by romanlab** [comment]
@Nikhil26112 what's the k8s version of your cluster?

**Comment by Nikhil26112** [comment]
> @Nikhil26112 Can you give some more context on the environment you tried to install in?
> 
> eks? fargate? minikube? do you have enough cpu/memory? maybe check for error logs in the deployment resource?
> 
> thx

I tried to install it on minikube. I have enough CPU memory.

**Comment by Nikhil26112** [comment]
> what's the k8s version of your cluster?

nikhil@nikhil:~$ kubectl version

WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.4", GitCommit:"872a965c6c6526caa949f0c6ac028ef7aff3fb78", GitTreeState:"clean", BuildDate:"2022-11-09T13:36:36Z", GoVersion:"go1.19.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3", GitCommit:"434bfd82814af038ad94d62ebe59b133fcb50506", GitTreeState:"clean", BuildDate:"2022-10-12T10:49:09Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

**Comment by Nikhil26112** [comment]
> @Nikhil26112 what's the k8s version of your cluster?

nikhil@nikhil:~$ kubectl version --short

Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.4
Kustomize Version: v4.5.7
Server Version: v1.25.3

**Comment by Nikhil26112** [comment]
This issue is resolved. 
I set token using
```datree config set token <token name>```
and then logged out and logged in again and this works now.
I successfully logged in to datree dashboard using my github.
Thank you

**Comment by royhadad** [comment]
@Nikhil26112

From my personal experience, when this happens on minikube it's usually because of insufficient cpu (minikube's default is 2)

Try installing Datree with this command instead to request less cpu:
```bash
helm install -n datree datree-webhook datree-webhook/datree-admission-webhook --create-namespace --set resources.requests.cpu=10m --set scanJob.resources.requests.cpu=10m --set datree.token=<YOUR_TOKEN>
```

**Comment by royhadad** [comment]
@Nikhil26112 
This is a workaround to access the dashboard, in order to install Datree in **minikube**, I suggest you take a look at this issue, there is a temporary workaround that should work:
https://github.com/datreeio/datree/issues/848

**Comment by Nikhil26112** [comment]
@royhadad 
Okay, I thought the issue is resolved that's why I got access to dashboard.
Thanks for the update.
