### ISSUE TITLE
Datree installation fails in Minikube due to insufficient cpu

### ISSUE THREAD

**Issue by royhadad** [datreeio/datree#848]
**There is a temporary workaround at the bottom of the issue**

**Describe the bug**
when trying to install Datree in my local minikube, I get the following error:
```
[debug] failed post-install: timed out waiting for the condition
```

**To Reproduce**
1. start minikube locally
2. apply some resources that will request some cpu
3. Install Datree using the one-liner https://github.com/datreeio/datree#2-install-datree-on-your-cluster

**Expected behavior**
Datree should be installed successfully on the local cluster

**Screenshots**
![203968620-7ffac4a9-9858-4d6f-8fbb-bb8ca577ccbb](https://user-images.githubusercontent.com/39004075/204134540-85aea395-9740-478d-bc31-664a502323d9.png)

**Datree version (run `datree version`):**
 - Version: datree-admission-webhook-0.3.14

**Temporary workaround**
Simply request less cpu for Datree resources (default is 1000m) when installing in a local minikube, either by editing the helm .values file, or using this one-liner instead:
```bash
helm install -n datree datree-webhook datree-webhook/datree-admission-webhook --create-namespace --set resources.requests.cpu=100m --set scanJob.resources.requests.cpu=100m --set datree.token=<TOKEN>
```

**Comment by Nikhil26112** [comment]
Is this issue resolved? @royhadad

**Comment by adifayer** [comment]
@Nikhil26112 Yes, the issue is resolved :)

**Comment by royhadad** [comment]
@Nikhil26112 Yep! By default, Datree is now installed without cpu request. When installing it on a production cluster, you should add cpu/memory requests and limits via the Values.yaml file
