### ISSUE TITLE
Datree Support for SOPS or ability to skip files where "sops" is contained

### ISSUE THREAD

**Issue by John-Limb** [datreeio/datree#855]
**Is your feature request related to a problem? Please describe.**
When scanning files encrypted with SOPS etc, Schema validation will fail. Evidently this is due to how sops structures the file (Example: https://github.com/John-Limb/Ansible-Lab-Automation/blob/e5a767f91afd369931e89613998d63e4bf57d220/lab/apps/guacamole/guacamole-configmap.yaml)
Whilst one can see you can skip certain other rules, you cannot skip files outright. 

**Describe the solution you'd like**
For the ability to either decrypt and scan files properly or to be able to just mark the file as having the ability to skip.

**Describe alternatives you've considered**
Looked at Skipping under the behaviors section of the website but no luck, Can only see certain rules can be skipped

**Additional context**

**Comment by hadar-co** [comment]
Hi @John-Limb, by default the schema validation step is strict, meaning it does not allow additional properties.

You can pass the --permissive-schema flag to suppress this, like this:

`datree test file.yaml --permissive-schema`

**Comment by John-Limb** [comment]
Ok, and the same would go for a CI integration where I add the CLI argument into my workflow YAML?

**Comment by hadar-co** [comment]
Yes:)

You can see many examples for various CI platforms here:
[https://hub.datree.io/cicd-examples](https://hub.datree.io/cicd-examples)

If you're using Github, you can use our official action:
[https://github.com/datreeio/action-datree#usage](https://github.com/datreeio/action-datree#usage)

**Comment by John-Limb** [comment]
Awesome, this has solved the errors :) 
Would still be awesome to validate encrypted files eventually though..

**Comment by eyarz** [comment]
@John-Limb feel free to open a new `enhancement` ticket and we will prioritize it...
