### ISSUE TITLE
Datree installation is failing

### ISSUE THREAD

**Issue by Rajat0002** [datreeio/datree#861]
helm install -n datree datree-webhook datree-webhook/datree-admission-webhook --debug \
install.go:192: [debug] Original chart version: ""
Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: \
helm.go:84: [debug] expected at most two arguments, unexpected arguments: \
helm.sh/helm/v3/pkg/action.(*Install).NameAndChart
        helm.sh/helm/v3/pkg/action/install.go:595
main.runInstall
        helm.sh/helm/v3/cmd/helm/install.go:198

C:\Windows\System32>                --create-namespace \
'--create-namespace' is not recognized as an internal or external command,
operable program or batch file.

C:\Windows\System32>                --set datree.token=75aa3046-179d-4eb2-bc23-513827589045 \
'--set' is not recognized as an internal or external command,
operable program or batch file.

**Comment by adifayer** [comment]
Hey @Rajat0002 :) Datree's webhook works only with Linux-based machines. If you're using windows, you can use WSL to install Datree. Don't forget that you need to have a connection and access to your cluster.
