### ISSUE TITLE
could not find schema for PodDisruptionBudget

### ISSUE THREAD

**Issue by pdeva** [datreeio/datree#867]
**Describe the bug**
datree fails with error when using kustomize module: 
`k8s schema validation error: could not find schema for PodDisruptionBudget`

**To Reproduce**
1. create folder `base` with `kustomization.yaml` that points to a `PodDisruptionBudget` resource
1. run `datree kustomize test base`

**Expected behavior**
should show no error

**Screenshots**
<img width="1094" alt="Screenshot 2023-01-18 at 7 17 56 PM" src="https://user-images.githubusercontent.com/3190176/213347417-f4ab46a8-4644-4cd4-ac82-9d8ed7f797ff.png">

**Desktop (please complete the following information):**
 - OS: macos ventura

**Datree version (run `datree version`):**
 - Version: 1.8.14

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: [e.g. C5fiX5Tm4SvxwkcfXVSHu5]

**Additional context**  
If possible, include a YAML file to reproduce the bug.

**Comment by eyarz** [comment]
`PodDisruptionBudget` became stable in [K8s version 1.21](https://kubernetes.io/docs/tasks/run-application/configure-pdb/).
From your screenshot, I can see that you are using schema version 1.20:
![image](https://user-images.githubusercontent.com/19731161/213384101-870508fc-3e00-4419-b3d0-a3fc4a12dfe6.png)

You need to change your default schema version to match your cluster version:
https://hub.datree.io/cli/schema-validation
