### ISSUE TITLE
Datree update causing validation errors on non-existent fields in deployment files

### ISSUE THREAD

**Issue by IAMManuel** [datreeio/datree#889]
Hello,

I'm writing to report an issue that we've encountered with a recent Datree update. We use Datree to validate our deployment files, and after the update, we started seeing validation errors on non-existent fields.

Specifically, Datree is now validating fields that do not exist in our deployment files, causing unnecessary errors and slowing down our development process. We believe this is due to a recent update in Datree's validation rules.

We would like to request that the validation rules be updated to exclude non-existent fields in the deployment file, or to provide an option to disable this type of validation. This would help us maintain our development speed and prevent unnecessary errors.

I've attached a lite version of our deployment file. As you could see, we don't use anything from the like of `GitHub secrets`, `Heroku secrets`,  `Okta secrets` and others in our file.

You can check the raw log and the yml file in the zip
[datree.zip](https://github.com/datreeio/datree/files/10850992/datree.zip)

**Comment by adifayer** [comment]
Hey @IAMManuel, thank you for reporting on this issue!
I was able to reproduce the bug, we're working on a fix as we speak :)

**Comment by adifayer** [comment]
@IAMManuel Can you please share which CLI version you used before the upgrade? (the version that doesn't reproduce the bug)
