### ISSUE TITLE
Error messages logged to stdout instead of stderr break Json and Yaml output formats

### ISSUE THREAD

**Issue by zmotu** [datreeio/datree#900]
**Describe the bug**
When an either 
a) an error is thrown 
b) running in offline mode
with `--output json` or `--output yaml` flag set, the resulting error messages are logged to stdout. This results in non conforment json or yaml output.  

**To Reproduce**
1. Run command 'datree test ./ --output json` in a directory containing no yaml files
2. See `no files detected` logged in non-json to stdout

1. Run command `datree config set offline local`
2. Run command `datree test ./ --no-record`

```
...
"evaluationSummary":{"configsCount":11,"filesCount":10,"passedYamlValidationCount":10,"k8sValidation":"10/10","passedPolicyValidationCount":7},"yamlValidationResults":null,"k8sValidationResults":null,"loginUrl":""}
[INFO] You're running Datree in offline mode

```

**Expected behavior**
Errors and warnings are logged to stderr so stdout so output can be compliant with the configured output format (eg. json or yaml). 

**Screenshots**
![Screenshot 2023-03-13 at 8 06 37 am](https://user-images.githubusercontent.com/2383784/224576562-d42b20e4-274a-4cce-b077-ff8b62903d2c.png)

**Desktop (please complete the following information):**
 - OS: MacOS

**Datree version (run `datree version`):**
 - Version: 1.8.39

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: ktqUgZurDdKM56Fe8kDJi7

**Additional context**  
Note that the latest version v1.8.39 introduced additional logging in offline mode which will result in output being no longer json or yaml compliant. Pre-existing issues with errors such as `no files detected` were already logged to stdout opposed to stderr so this is still a bug in addition to the regression.

**Comment by adifayer** [comment]
@zmotu Thank you for opening this issue. We're looking into it right now, a fix will be released soon :)
