### ISSUE TITLE
Datree outage?

### ISSUE THREAD

**Issue by noorul** [datreeio/datree#967]
**Describe the bug**
Looks like datree is not reachable

**To Reproduce**
1. Run ```datree kustomize test /path/to/kuztomize/folder```

**Expected behavior**
datree should run without any errors

**Screenshots**

```
Failed since internet connection refused, you can use the following command to set your config to run offline:
datree config set offline local
```

**Desktop (please complete the following information):**
 - OS: MacOS/Linux
 
**Datree version (run `datree version`):**
 - Version: 1.9.19

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: VUQVVkcTMTCMexheQZWeih

**Additional context**  
N/A

**Comment by NikolaiThingnesLeira** [comment]
Looks like the project has been deprecated, have to use offline mode or a new tool

**Comment by noorul** [comment]
So sad that this project is in this state

**Comment by Bandarisandeep26** [comment]
im also
