### ISSUE TITLE
get.datree.io is down

### ISSUE THREAD

**Issue by leasley199** [datreeio/datree#968]
**Describe the bug**
Unable to resolve get.datree.io

**To Reproduce**
```sh
curl https://get.datree.io | /bin/bash
#curl: (6) Could not resolve host: get.datree.io
```

**Expected behavior**
Datree CLI is installed

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS:  linux

**Datree version (run `datree version`):**
 - Version: any

**Client ID (`cat ~/.datree/config.yaml`):**
 - client_id: NA

**Additional context**  
If possible, include a YAML file to reproduce the bug. 

using nslookup against cloudflare, google and opendns get.datree.io is not resolvable.

**Comment by royhadad** [comment]
the product is deprecated, so all the servers are down.
if you would like to use the software as an offline standalone, you may download the latest version from the github repo's releases

**Comment by leasley199** [comment]
Is there plans to update the public facing site?
