### ISSUE TITLE
owner label check not working

### ISSUE THREAD

**Issue by jmatis-bullhorn** [datreeio/datree#97]
**Describe the bug**
When 'owner' label check enabled helm datree test does not fail  on chart that does not have this label

**To Reproduce**
Steps to reproduce the behaviour:
1. Run command '$ helm datree test hawtio'
2. output does not show any error despite my settings in 

**Expected behavior**
i was expecting it to fail since my chart does not have that label 

**Screenshots**
my deployment yaml starts with: 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $chartname }}-{{ $branchName }}
  labels:
    app: {{ $chartname }}
    branch: {{ $branchName }}
spec:

[hawtio]$ grep -ir owner *
[hawtio]$

**Desktop (please complete the following information):**
 - OS: Linux

**Datree version (run `datree verion`):**
 - Version: 0.1.741

**Additional context**  
(Summary)WWWW
WWWWWWWWWWWWW
- Passing YAML validation: 1/1
WWWWWWWWWWWWW
- Passing Kubernetes (1.18.0) schema validation: 1/1
WWWWWWWWWWWWW
- Passing policy check: 1/1
WWWWWWWWWWWWW
+-----------------------------------+----------------------------------------------------------+
| Enabled rules in policy “Default” | 29                                                       |
| Configs tested against policy     | 2                                                        |
| Total rules evaluated             | 29                                                       |
| Total rules failed                | 0                                                        |
| Total rules passed                | 29                                                       |
| See all rules in policy           | https://app.datree.io/login?cliId=Aq6F7RCReLipvMRNp9V... |
+-----------------------------------+----------------------------------------------------------+
[charts]$

**Comment by eyarz** [comment]
Thank you for reporting that!
I'm not able able to reproduce this bug :/

Can you please try to [generate a manifest file](https://helm.sh/docs/helm/helm_template/#helm-template) and run `datree test [manifest file]` against it?
It will help us to debug this issue and understand if this is a logical problem with the policy engine or the helm plugin.
