### ISSUE TITLE
Login and Get Started not working on datree website

### ISSUE THREAD

**Issue by smolsuryansh** [datreeio/datree#974]
**Describe the bug**
When I click on "Get Started" or "Login" on the Datree website. I get a "We can’t connect to the server at app.datree.io" error. 

**To Reproduce**
1. Go to Datree website (Make sure you are not logged in)
2. Click on Get Started or Log In
3. You will get an error messge saying "We can’t connect to the server at app.datree.io"

**Screenshots**
![datree-error](https://github.com/datreeio/datree/assets/144353958/1e6927d5-472e-4429-9c7c-12ea4c903ad8)

**Desktop (please complete the following information):**
 - OS: Debian 12

**Comment by VDXD** [comment]
same issue with me on windows 11

**Comment by JakobClausen** [comment]
I get the same when running 
`curl https://get.datree.io | /bin/bash`

**Comment by mrpbennett** [comment]
I just checked the last commit

```
[Datree](https://www.datree.io/) (pronounced `/da-tree/`) was built to secure Kubernetes workloads by blocking the deployment of misconfigured resources. **Since July 2023, the commercial company that supports and actively maintains this project has been closed.
```
DaTree is dead.

**Comment by smolsuryansh** [comment]
> I just checked the last commit
> 
> ```
> [Datree](https://www.datree.io/) (pronounced `/da-tree/`) was built to secure Kubernetes workloads by blocking the deployment of misconfigured resources. **Since July 2023, the commercial company that supports and actively maintains this project has been closed.
> ```
> 
> DaTree is dead.

Are there any good alternatives like DaTree?

**Comment by mrpbennett** [comment]
@smolsuryansh take a look at https://kubescape.io/docs/getting-started/

**Comment by RoshanAnsy** [comment]
same issue with me on windows 11.

**Comment by smolsuryansh** [comment]
> same issue with me on windows 11.

as mentioned by @mrpbennett, sadly datree is dead.

**Comment by Developer-SAIF** [comment]
Today I also tried to access Datree login page for the first time.
But failed to do so.
