### ISSUE TITLE
app.datree.io NXDOMAIN

### ISSUE THREAD

**Issue by borgermeister** [datreeio/datree#977]
Hi

Not sure if this is the right place to report this issue...but here goes.

I am unable to try out Datree since the login URL is not accessible.

```bash
nslookup
> set type=ns
> datree.io
Server:		9.9.9.9
Address:	9.9.9.9#53

Non-authoritative answer:
datree.io	nameserver = ns-609.awsdns-12.net.
datree.io	nameserver = ns-136.awsdns-17.com.
datree.io	nameserver = ns-1422.awsdns-49.org.
datree.io	nameserver = ns-1612.awsdns-09.co.uk.

> server ns-609.awsdns-12.net
Default server: ns-609.awsdns-12.net
Address: 205.251.194.97#53
> app.datree.io
Server:		ns-609.awsdns-12.net
Address:	205.251.194.97#53

** server can't find app.datree.io: NXDOMAIN

> server ns-1422.awsdns-49.org
Default server: ns-1422.awsdns-49.org
Address: 205.251.197.142#53
> app.datree.io
Server:		ns-1422.awsdns-49.org
Address:	205.251.197.142#53

** server can't find app.datree.io: NXDOMAIN
```

I've tried to resolve the address of `app.datree.io` from several nameservers but all replies with NXDOMAIN.

**Comment by freethejazz** [comment]
Per the readme, the company previously running Datree has closed and datree is now available only in offline mode. If you still want to try, your best bet is to download the most recent release: https://github.com/datreeio/datree/releases/tag/1.9.19
